### ISSUE TITLE
Rangeset issue

### ISSUE THREAD

**Issue by TheHuangs** [Pyomo/pyomo#1056]
I built one set HP and one parameter Hh as shown below, HP has two elements(model.HP[1] and model.HP[2])， while parameter Hh only have one element(model.Hh[1]=0.5), I can not retrive the value of Hh[2]. 
```python
model = ConcreteModel()
model.HP = RangeSet(1, 2,  doc="set of hot process streams i"          )
model.Hh   = Param(model.HP, default=[1,0.5], doc="heat transfer coefficient for hot stream i"  )
```

**Comment by jsiirola** [comment]
This is expected behavior.

Initializers (arguments to `initialize=` or `default=`) are expected to be "dict-like", and Param looks up values based on the index.  So, when `Hh` is being constructed, it looks up 1 in the `default` initializer and gets the second element of the list (since Python lists are 0-indexed).  When it then looks up 2, it finds that 2 is not in the default, so the Param is left undefined (Pyomo supports sparse Param objects).

The solution to get the behavior that I *think* you want is either:

```
model.Hh = Param(model.HP, default=[None, 1, 0.5])
```
or
```
model.Hh = Param(model.HP, default={1:1, 2:0.5})
```
