### ISSUE TITLE
Update ZIPFILE creation

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#112]
This should be synchronized with the tools installed with:

  pyomo install-extras

and

  conda install pyomo.extras

**Comment by jsiirola** [comment]
I am not keen on including pyomo-extras in the zipfile.  The extras include dependencies on some fairly complex packages (notably `numpy`, `scipy`, and `matplotlib`).  These are difficult to reliably bundle and even more tricky to build/install from source.  As the zipfile is meant to be used for offline installations on any architecture (and with `pyomo_install`), bundling these heavyweight packages is not something that I really want to try and support.

**Comment by whart222** [comment]
What is the principle for including codes in the zipfile?  They are native Python packages?

**Comment by jsiirola** [comment]
The original principle was to include everything that we expected a "standard" Pyomo installation to have available.  So, this included the required dependencies as well as the "expected" optional dependencies like `pyro`.  I believe that we excluded all non-pure-python packages (like `pyyaml`) because that made offline installation on Windows very challenging.

**Comment by whart222** [comment]
We never defined a "standard" Pyomo installation, but rather the line got drawn at non-pure-python packages.  I'm OK if that's the standard used for the ZIP file as well.

Since that's a different list from what we have in pyomo.extras, we'll probably need to keep this list separate.

**Comment by mrmundt** [comment]
No longer relevant.
