### ISSUE TITLE
Feature Request: Compute covariance matrix with ParmEst

### ISSUE THREAD

**Issue by adowling2** [Pyomo/pyomo#1259]
Is it on the roadmap to compute the covariance matrix in ParmEst based on a local linearization? If not, I may contribute this during the next few weeks.

**Comment by kaklise** [comment]
We have talked about adding the covariance matrix to parmest, but do not have plans to include that in the short term.  That contribution would be great.

**Comment by notesofdabbler** [comment]
It looks like the current API for [theta_est](https://pyomo.readthedocs.io/en/stable/contributed_packages/parmest/api.html) indicates that a hessian is returned if solver 'k_aug' is used. So the covariance matrix could be computed from that. But I am assuming 'k_aug' needs to be installed separately. Also, it looks like [pynumero](https://github.com/Pyomo/pyomo/tree/master/pyomo/contrib/pynumero) might also be a good option to look into since it is built to get gradient and hessian from a pyomo model. But there might be the extra step of computing reduced hessian in the space of just the parameters that are estimated.

**Comment by adowling2** [comment]
@kaklise I hope to find time during the next week to add this feature. I'll post again when I have something working in a fork/pull request. This will likely require some changes to the ParmEst interface. But let's cross that bridge once I get a prototype working.

@carldlaird @michaelbynum For my initial prototype, I plan to use your recently contributed reduced Hessian code:
https://github.com/Pyomo/pyomo/blob/master/pyomo/contrib/interior_point/inverse_reduced_hessian.py

**Comment by adowling2** [comment]
I have a prototype working! But I need help linking this issue with my draft PR.

**Comment by blnicho** [comment]
@adowling2 all you have to do is type "#" followed by the issue number and GitHub is smart enough to link them.
