### ISSUE TITLE
What are '_shared_args'?

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#1270]
`SumExpression` defines a slot `_shared_args`: https://github.com/Pyomo/pyomo/blob/03c05940a6d764ff70473e0dd509752493b429b3/pyomo/core/expr/numeric_expr.py#L954

What does it do?

**Comment by jsiirola** [comment]
The Pyomo5 expression rewrite changed the set of "promises" in the Pyomo expression tree.  Previously, all expression trees were guaranteed to be independent.  This meant we had logic to detect cases similar to the following:
```python
a = m.x + m.y
b = a + m.z
```
so that we would end up with
```
a := SumExpression(args=[m.x, m.y])
b := SumExpression(args=[m.x, m.y, m.z])
```
The problem with "expression detangling" is that the following ends up having a O(n**2) scaling:
```python
ans = 0
for i in m.I:
    ans = ans + m.x[i]
```
Pyomo5 Expressions changed this to allow for expression trees to contain common subexpressions.  In exchange, the expression system requires that all nodes in the expression tree are *immutable*.  This caused challenges with large summations, where for efficiency and sanity reasons we need to create large n-ary operator nodes.  The solution was to make SumExpression a "view" to a potentially shared list of operands.  The view would contain a flag (nargs) to know how many elements in the list should be summed for this node (i.e., the contract is that the list of operands would only grow - anything that violates that contract forces the expression system to copy the shared list).  So, in the new system, the above example would cause the following:
```
a := SumExpression(_nargs=2, _shared_args=[m.x, m.y, m.z])
b := SumExpression(_nargs=3, _shared_args=[m.x, m.y, m.z])
```

**Comment by jsiirola** [comment]
Ack.  I should not answer questions from memory.  While everything I said above is correct, the meaning of `_shared_args` was not.  `_shared_args` is a flag indicating the likehood that another SumExpression is pointing to the same `_args_` list.  It *should* be redundant information (I believe that it should always have the same value as `len(self._args_) == self._nargs`).

**Comment by qtothec** [comment]
Gotcha. Was wondering if I needed to replicate it for `AndExpression` and `OrExpression`, but looks like should be fine without for now, since the logical expression system doesn't have as much sophistication yet.
