### ISSUE TITLE
Converting double-inequality to equality

### ISSUE THREAD

**Issue by ghackebeil** [Pyomo/pyomo#131]
There is code built into the expression generation system that will convert a double-inequality expression into an equality expression for certain special cases. This seems like a micro-optimization and recently led to an error that was very difficult to debug.

In a effort to simplify our code and reduce confusion, should we remove this?

**Comment by jsiirola** [comment]
I would not recommend removing the conversion.  The reason for it is that when processing chained (double) inequalities, we cannot tell the difference between “a <= b <= a” and “b >= a >= b”.  Instead of just randomly guessing the first form, we "play it consistent" and convert both forms into the (mathematically correct) equality constraint.

**Comment by ghackebeil** [comment]
That makes sense.
