### ISSUE TITLE
Should inconsistent variable bounds and domain cause an exception

### ISSUE THREAD

**Issue by michaelbynum** [Pyomo/pyomo#1327]
Consider the following

```
>>> import pyomo.environ as pro
>>> m = pyo.ConcreteModel()
>>> m.x = pyo.Var(bounds=(0, 2), domain=pyo.Binary)
```

This currently does not cause an exception. Instead it changes the bounds to (0, 1). Should it raise an exception? What if the user meant to make the domain `Integer`?

**Comment by emma58** [comment]
I think this should raise an exception because it is completely unclear which piece of conflicting information should "win" in this case. What's written doesn't make sense, and it seems arbitrary that Binary is what will actually happen.

**Comment by michaelbynum** [comment]
I think I agree.

**Comment by carldlaird** [comment]
I also agree.

**Comment by jsiirola** [comment]
For what it's worth, in the set rewrite, the Set component treats `domain`, `within`, and `bounds` as synonyms.  If the user provides more than one, then the effective domain is the intersection of the individual sets.

For Var, I could probably go one of two ways:
- Throw an exception if the bounds are not in the domain
- Accept anything as a bound, but when reporting the bounds, report the tighter of the domain bound and the lower/upper bounds

I believe the second is more consistent with kernel, where domain bounds are mapped onto the numeric bounds immediately, and the domain is either RealSet or IntegerSet.

The problem I see with the first approach is the following:
- create a model with, e.g. Binary variables
- relax the model by applying the "relax discrete variables" transformation (let's say in place)
- perform bounds tightening.  Let's assume some of the (now continuous) variables have fractional bound values
- undo the relaxation.  Should this now generate an exception, just because the bounds that are on a variable are not valid in the new variable domain (that is, the domain is more restrictive than the bounds)?

**Comment by michaelbynum** [comment]
Variable bounds return the the intersection of the bounds and the domain (min for the `ub` and max for the `lb`). Also, expression for this can now be obtained with `v.lower` and `v.upper`. I think this is well-defined, so I am going to close this.
