### ISSUE TITLE
Multiprocessing model generation

### ISSUE THREAD

**Issue by yas-97** [Pyomo/pyomo#1384]
I am trying to create models in stages: 
1 - The first is to make model with all variables, parameters, sets..
2 - Take the model from 1 and create constraints in separate models (using multiprocessing)
3 - Add the constrains blocks back to the master model.

I am having trouble with "3" how can i add blocks together under one model without breaking references? How will this change if I would pickle/unpickle the blocks before adding them together?

This is an example of what i have now:

```
 with ProcessPoolExecutor() as executor:
        # Generate constraints
        const_Sys = executor.submit(const_sys, model)
        const_Tech = executor.submit(const_tech, inp_data, model)
        const_Net = executor.submit(const_net, model)
        const_Stg = executor.submit(const_stg, inp_data, model)
        const_CO2 = executor.submit(const_co2, model)
        const_Cost = executor.submit(const_cost, model)
        gen_Custom = executor.submit(gen_custom, inp_data, model)
 processes = [const_Sys, const_Tech, const_Net, const_Stg, const_CO2, const_Cost, gen_Custom]
 ids = []
 blocks = []
  for process in processes:
        id = process.result()
        ids.append(id)
        block = ctypes.cast(id, ctypes.py_object).value
        blocks.append(block)
  for block in blocks:
        model.transfer_attributes_from(block)
```

**Comment by yas-97** [comment]
This is an example of what i have now:

`    with ProcessPoolExecutor() as executor:
        # Generate constraints
        const_Sys = executor.submit(const_sys, model)
        const_Tech = executor.submit(const_tech, inp_data, model)
        const_Net = executor.submit(const_net, model)
        const_Stg = executor.submit(const_stg, inp_data, model)
        const_CO2 = executor.submit(const_co2, model)
        const_Cost = executor.submit(const_cost, model)
        gen_Custom = executor.submit(gen_custom, inp_data, model)
    processes = [const_Sys, const_Tech, const_Net, const_Stg, const_CO2, const_Cost, gen_Custom]
    ids = []
    blocks = []
    for process in processes:
        id = process.result()
        ids.append(id)
        block = ctypes.cast(id, ctypes.py_object).value
        blocks.append(block)
    for block in blocks:
        model.transfer_attributes_from(block)
`

**Comment by jsiirola** [comment]
In theory what you have written is valid (or close to valid), but my guess is that it will not work as you intend.  The reason is that everything sent to the subprocesses must be pickled, and that process breaks the "connection" between the source model and what was created in the subprocesses.  I am assuming your functions (e.g., `const_sys`) return the partially populated model.  When that gets pickled on the subprocess and returned to the main process, the block shows up with a completely independent copy of variables / parameters from the ones that you started with.  So even though you have created and returned constraints, those constraints refer to different variables from the variables in the original model (so the blocks are still independent)
```python
>>> from concurrent.futures import ProcessPoolExecutor
>>> 
>>> from pyomo.environ import *
>>> m = ConcreteModel()
>>> m.x = Var()
>>> m.y = Var()
>>> 
>>> def build_con(m):
...    m.c = Constraint(expr=m.x + m.y == 0)
...    return m
... 
>>> subprocesses = []
>>> with ProcessPoolExecutor() as exe:
...     subprocesses.append( exe.submit(build_con, m) )
...     # ...
... 
>>> blk = subprocesses[0].result()
>>> 
>>> m.pprint()
2 Var Declarations
    x : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :  None :  None :  None : False :  True :  Reals
    y : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :  None :  None :  None : False :  True :  Reals

2 Declarations: x y
>>> blk.pprint()
2 Var Declarations
    x : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :  None :  None :  None : False :  True :  Reals
    y : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :  None :  None :  None : False :  True :  Reals

1 Constraint Declarations
    c : Size=1, Index=None, Active=True
        Key  : Lower : Body  : Upper : Active
        None :   0.0 : x + y :   0.0 :   True

3 Declarations: x y c
>>> m.x is blk.x
False
```

The simplest thing to do would be to add additional constraints that couple the variables between among the blocks (and rely on the solver presolve to remove the constraints/redundant variables); for example:
```python
m.linkingCons = ConstraintList()
m.subblock_idx = Set(initialize=range(len(subprocesses)))
m.subblocks = Block(m.subblock_idx)
for idx, sp in enumerate(subprocesses):
    m.subblocks[i].transfer_attributes_from(sp.result())
    m.linkingCons.add(m.x == m.subblocks[i].x)
    m.linkingCons.add(m.y == m.subblocks[i].y)
```

You could attempt to "clean up" the constraints that were returned from the subprocess by substituting the Params/Vars returned from the subprocess with their counterparts from the original model (i.e., implement what the linear solver presolve would do for you; probably not worth it for MIPs but might be worth doing for NLPs).  Alternatively, there might be a way to build some form of "parallel aware" pickler that could preserve the linkages between the master and subprocess variables and do that conversion automatically as part of the unpickle process, but that would likely be a significant undertaking.

Regardless, in my experience, pickling/unpickling a model can be slower than generating it.  That is, you will spend more time moving the data between the processes than simply creating the entire model (in serial) to begin with.

Finally, I am closing this issue, as it is not an issue with Pyomo.  In the future, user support questions should leverage either StackOverflow or the pyomo-forum Google group.

**Comment by yas-97** [comment]
Thank you for your prompt response!
