### ISSUE TITLE
Reconstruct() does not work for continuous sets. Dirty workaround found, but unsatisfactory.

### ISSUE THREAD

**Issue by KennedyPutraKusumo** [Pyomo/pyomo#1413]
Hi all,

I have a script that: instantiates a Concrete model instance, a pyomo.dae simulator, and defines a function that simulates the model for various controls, parameters, and sampling times. An issue is that I am looking to pass in changing sampling times to the function. 

Documentation on pyomo.dae suggests to specify the sampling times when the continuous set is created. My (original) code will call the simulate function repeatedly, passing in varying values for sampling_times. A challenge is I do not know a-priori how many times the simulate function will be called, and what the sampling times in each call will be. This prevents the trivial solution of initializing the continuous set with the union of all the sampling times.

For now, I have found a work around of my own. But, it is not as clean as it should be. I feel that the reconstruct() method should be the cleanest way for doing this. However, invoking the method (with and without passing any inputs) does not seem to work; would be perfect if we could just pass in the new sampling_times to the reconstruct method.

Please let me know of any suggested way of achieving this. See below for the code, but note that the sampling times were given in this case. I have taken out the bit where the various sets of sampling times (and controls) are proposed. For simplicity, I have a simple code where I have two different sets of sampling times.

```python
from pyomo import dae as pod
from pyomo import environ as po
from matplotlib import pyplot as plt
import numpy as np


from pydex.core.designer import Designer


def simulate(model, simulator, ti_controls, sampling_times, model_parameters):
    """ fixing the control variables """
    # time-invariant
    model.theta_0.fix(model_parameters[0])
    model.theta_1.fix(model_parameters[1])
    model.alpha_a.fix(model_parameters[2])
    model.alpha_b.fix(0)
    model.nu.fix(model_parameters[3])
    # model.nu.fix(1)

    model.tau.fix(max(sampling_times))
    model.ca[0].fix(ti_controls[0])
    model.cb[0].fix(0)
    model.temp.fix(ti_controls[1])
    # no time-varying control for this example

    """ ensuring pyomo returns state values at given sampling times """
    model.t.initialize = np.array(sampling_times) / model.tau.value
    model.t.order_dict = {}  # to suppress pyomo warnings for duplicate elements
    model.t._constructed = False  # needed so we can re-initialize the continuous set
    model.t._data = {}
    model.t._fe = []
    model.t.value_list = []
    model.t.construct()  # line that re-initializes the continuous set

    """ simulating """
    simulator.simulate(integrator='idas')
    simulator.initialize_model()

    """" extracting results and returning it in appropriate format """
    normalized_sampling_times = sampling_times / model.tau.value
    ca = np.array([model.ca[t].value for t in normalized_sampling_times])
    cb = np.array([model.cb[t].value for t in normalized_sampling_times])

    return np.array([ca, cb]).T


def create_model():
    """ defining the model """
    model = po.ConcreteModel()
    model.t = pod.ContinuousSet(bounds=(0, 1))
    model.tau = po.Var()

    model.temp = po.Var()

    model.ca = po.Var(model.t, bounds=(0, 50))
    model.cb = po.Var(model.t, bounds=(0, 50))
    model.dca_dt = pod.DerivativeVar(model.ca, wrt=model.t)
    model.dcb_dt = pod.DerivativeVar(model.cb, wrt=model.t)

    model.theta_0 = po.Var()  # model parameters
    model.theta_1 = po.Var()
    model.alpha_a = po.Var()
    model.alpha_b = po.Var()
    model.nu = po.Var()

    def _material_balance_a(m, t):
        k = po.exp(m.theta_0 + m.theta_1 * (m.temp - 273.15) / m.temp)
        return m.dca_dt[t] / m.tau == - k * (m.ca[t] ** model.alpha_a) * (
                model.cb[t] ** model.alpha_b)

    model.material_balance_a = po.Constraint(model.t, rule=_material_balance_a)

    def _material_balance_b(m, t):
        k = po.exp(m.theta_0 + m.theta_1 * (m.temp - 273.15) / m.temp)
        return m.dcb_dt[t] / m.tau == m.nu * k * (m.ca[t] ** model.alpha_a) * (
                model.cb[t] ** model.alpha_b)

    model.material_balance_b = po.Constraint(model.t, rule=_material_balance_b)

    return model


pre_exp_constant = 0.1
activ_energy = 5000
theta_0 = np.log(pre_exp_constant) - activ_energy / (8.314159 * 273.15)
theta_1 = activ_energy / (8.314159 * 273.15)

model_1 = create_model()
simulator_1 = pod.Simulator(model_1, package='casadi')

spt = np.linspace(0, 100, 10)
out = simulate(
    model_1,
    simulator_1,
    ti_controls=np.array([1, 303.15]),
    sampling_times=spt,
    model_parameters=np.array([theta_0, theta_1, 1, 1]),
)

fig, axes = plt.subplots(1, 1)
axes.plot(spt, out[:, 0], label="c_a")
axes.plot(spt, out[:, 1], label="c_b")
axes.legend()

spt2 = np.linspace(0, 200, 15)
out2 = simulate(
    model_1,
    simulator_1,
    ti_controls=np.array([1, 303.15]),
    sampling_times=spt2,
    model_parameters=np.array([theta_0, theta_1, 1, 1]),
)

fig2, axes2 = plt.subplots(1, 1)
axes2.plot(spt2, out2[:, 0], label="c_a")
axes2.plot(spt2, out2[:, 1], label="c_b")
axes2.legend()
plt.show()

```

**Comment by blnicho** [comment]
@KennedyPutraKusumo is your intention to discretize the model using sampling points somehow determined by running the simulator?

The `reconstruct` method is currently broken, see #252, so I wouldn't recommend going that route. I just did a quick test and you might be able to do something like this:

```
from pyomo.environ import *
from pyomo.dae import *

m = ConcreteModel()
m.t = ContinuousSet(bounds=(0,10))
m.x = Var(m.t)
m.dx = DerivativeVar(m.x)

def _con(m, t):
    return m.dx[t] == m.x[t]
m.con = Constraint(m.t, rule=_con)

# Add sampling points just before applying a discretization transformation
m.t.add(1,2,3,4,5)
# Apply discretization transformation
TransformationFactory('dae.finite_difference').apply_to(m, nfe=10)
```

If I then run `m.t.pprint()` I get:
```
>>> m.t.pprint()
t : Dim=0, Dimen=1, Size=11, Domain=None, Ordered=Sorted, Bounds=(0, 10)
    [0, 1, 2, 3, 4, 5, 5.625, 6.25, 7.5, 8.75, 10]
```
and the model appears to be discretized correctly. If you decide to go with this approach I recommend waiting until right before the discretization to add the sampling points otherwise you may get some unexpected behavior. 

Also be very careful with any constraints or objective functions that sum over elements in the ContinuousSet.

**Comment by KennedyPutraKusumo** [comment]
Thanks Bethany.

My intention is that the model will be discretized using different sampling times. The simulate function is part of an experimental design problem. The different sampling times will be proposed by my optimizer.

And the m.t.add() route is part of what I was looking for. The other part was m.t.remove() to remove all unnecessary sampling times (prevent increasing number discretized points for large experimental design problems). I will ensure to remove and add elements before discretizing. A minor problem, since I need to ensure to add or remove elements before discretization, is there any way to un-discretize my model? I could rebuild my model from scratch every time simulate is called, but it would lead to performance loss; especially for large models.

About summing over continuous sets. Thanks for the tip! I presume a basic fix would be to make sure to normalize the sums over the number of elements in the discretized continuous set.

**Comment by blnicho** [comment]
Removing points from the ContinuousSet will not work. The problem is that the discretization transformation is only set up to add additional indices to components indexed by the ContinuousSet and it will not check if any indices need to be removed. Under-the-hood, Pyomo is creating component objects for every index in the ContinuousSet when the model is constructed and then the discretization transformation will 1) expand the ContinuousSet with new discretization points 2) create new component objects for any new indices in the ContinuousSet and 3) Add discretization equations for any DerivativeVar components. There is no way to "un-discretize" your model.

The most robust approach will probably be to rebuild/rediscretize the model every time instead of trying to add/remove points on-the-fly. You might be able to clone the model after it has been constructed but before applying the discretization transformation to reduce a little bit of the overhead but I wouldn't expect it to be a significant performance improvement.

To better understand my comment about summing over the elements in the ContinuousSet consider the following:

```
m = ConcreteModel()
m.t = ContinuousSet(bounds=(0,10))
m.v = Var(m.t)

def _con1(m):
    return sum(m.v[i] for i in m.t) <= 10
m.con1 = Constraint(rule=_con1)

TransformationFactory('dae.finite_difference').apply_to(m, nfe=2)

def _con2(m):
    return sum(m.v[i] for i in m.t) <= 10
m.con2 = Constraint(rule=_con2)
```

Notice that the rules for `con1` and `con2` are **identical** but one of them comes before the discretization and one comes after. If I print out both constraints I get the following:
```

2 Constraint Declarations
    con1 : Size=1, Index=None, Active=True
        Key  : Lower : Body         : Upper : Active
        None :  -Inf : v[0] + v[10] :  10.0 :   True
    con2 : Size=1, Index=None, Active=True
        Key  : Lower : Body                  : Upper : Active
        None :  -Inf : v[0] + v[5.0] + v[10] :  10.0 :   True
```
Notice that the constraint expressions are **different**. This is because the sum is only over the points that exist in the ContinuousSet `t` up to the point that the constraint was constructed.

**Comment by KennedyPutraKusumo** [comment]
Thanks Bethany, I have a better picture now. I will resort to rebuilding the model each time then. Since cloning the model could significantly increase memory requirement.

And thanks for the in-depth help with sum over the continuous sets; got it! Before construction, the continuous set will only have the given lower and upper bound as elements; meaning constructing constraints that sums over these elements will be different before and after the discretization.
