### ISSUE TITLE
Slicer does not support display and does not give error message

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#155]
**Desired** behavior: display all elements of x that have 'A' as the first index.
**Expected** behavior: an error if that is not supported
**Actual** behavior: nothing happens
```
>>> from pyomo.environ import *
>>> m = ConcreteModel()
>>> m.x = Var(['A', 'B'], [1, 2])
>>> m.x.display()
x : Size=4, Index=x_index
    Key      : Lower : Value : Upper : Fixed : Stale : Domain
    ('A', 1) :  None :  None :  None : False :  True :  Reals
    ('A', 2) :  None :  None :  None : False :  True :  Reals
    ('B', 1) :  None :  None :  None : False :  True :  Reals
    ('B', 2) :  None :  None :  None : False :  True :  Reals
>>> m.x['A', :].display()
<pyomo.core.base.indexed_component._IndexedComponent_slicer object at 0x7fe3089312d0>
>>>
```

**Comment by jsiirola** [comment]
Slicing in Pyomo components produces a *generator*.  The fact that we allow cached indirection (i.e., putting additional method calls after the initial slice / `__getitem__`) does not negate the fact that we fundamentally will return a generator.  As such, it should always either be used in a `for` loop or in something that expects a generator (e.g., list comprehension).  So, in theory, you could do:

```python
for _ in m.x['A', :].display():
    pass
```
That is, the method returns nothing, so you don't have to do anything in the loop body.  Unfortunately, this specific code doesn't work because `_VarData` objects don't implement `display()` (that is only implemented on `Component` and not `ComponentData`).  This deficiency has been mentioned before among the developers, but I don't immediately see the ticket for it.

It is possible that we could toss a warning when an `_IndexedComponent_slicer` is created but falls out of scope without ever being iterated over.  I can't immediately think of a situation where creating the slicer and never using it would be desirable behavior.

**Comment by qtothec** [comment]
That makes sense, though it's not very satisfying. I can almost guarantee that of the people who have discovered slicers, I am not the only one who has tried to `display()` a slice of a large indexed variable.

There is definitely a use case for being able to quickly visualize a slice of an `IndexedComponent`.

**Comment by blnicho** [comment]
A couple other use-cases that would be convenient would be fixing a variable slice or deactivating a constraint slice:

    m.x['A', :].fix(10)

    m.con['A', :].deactivate()

**Comment by jsiirola** [comment]
The developers discussed this today and we are proposing redefining the role of `__call__` when creating an `_IndexedComponent_slicer`.  That was the least useful of the three "magic methods" that made slicing work (the others being `__getattr__` and `__getitem__`).  In the new world, `__call__` will not extend the slice, but will instead trigger the slicer to iterate over the slice and call the method.

**Comment by jsiirola** [comment]
The alternative is to get rid of the `_IndexedComponent_slicer` entirely and instead have the slice notation return a temporary `IndexedComponent`.  This would have several benefits (e.g., `.display()` would work more intuitively, but would also prevent nested slices (e.g., `m.x[1,:].y[...]`)

**Comment by jsiirola** [comment]
The slicer has been updated so that `__call__`ing the slicer will cause it to iterate over itself and call the identified attribute.  @blnicho's examples should both work.  @qtothec's original `display()` example will produce an error because `_GeneralVarData` does not implement a `display` method.   To support that behavior we would need to create a temporary `IndexedVar`, populate it's `_data` with just the results of the slice and then call the `IndexedVar`'s `display()`.

**Comment by jghouse88** [comment]
I came across a case where I needed sliced `var` and was glad to find this has already been raised and resolved. 
@jsiirola Quick question; with the update if I do something like  (using Qi's example):
`temp_x = m.x['A', :]`
I am not sure whether temp_x will now be an `IndexedVar` or an `IndexedComponent`?

**Comment by jsiirola** [comment]
The introduction of the `Reference` function fully resolves this issue.  @qtothec's original use case can be accomplished with:
```
>>> from pyomo.environ import *
>>> m = ConcreteModel()
>>> m.x = Var(['A', 'B'], [1, 2])
>>> m.x.display()
x : Size=4, Index=x_index
    Key      : Lower : Value : Upper : Fixed : Stale : Domain
    ('A', 1) :  None :  None :  None : False :  True :  Reals
    ('A', 2) :  None :  None :  None : False :  True :  Reals
    ('B', 1) :  None :  None :  None : False :  True :  Reals
    ('B', 2) :  None :  None :  None : False :  True :  Reals
>>> Reference(m.x['A', :]).display()
IndexedVar : Size=2, Index=x_index_1
    Key : Lower : Value : Upper : Fixed : Stale : Domain
      1 :  None :  None :  None : False :  True :  Reals
      2 :  None :  None :  None : False :  True :  Reals
```
The reason the Reference is needed goes back to @jghouse88's question: `m.x['a',:]` returns a `_IndexedComponent_slice` object.  To get a "proper" component (which implements the `display()` method, `Reference` will return (in this case) an `IndexedVar`.  See the documentation for `Reference` (currently inline in `pyomo/core/base/reference.py`) for more information on ctype handling.
