### ISSUE TITLE
How to print values of functions in pymoso

### ISSUE THREAD

**Issue by chuongask** [Pyomo/pyomo#1586]
Hi all,
I am trying to print the values of functions implemented in pymoso but encourntered an issue. Please look at the following code and let me know some your advice if you know.  In the following code, my question is how to print the value of (model.f1,model.f2,model.f3) and then plot them? Thank you very much in advance for your kind help.

#simple example called: MHH.py in pyomo
import pyomo.kernel as pmo
from pyomo.environ import *
import numpy as np
from numpy import empty
model = ConcreteModel()
model.n = Param(initialize = 2, within = Integers) #value(model.n)=1
model.x1 = Var(bounds=(0,1))
model.x2 = Var(bounds=(0,1))
model.f1 = (model.x1-0.8)**2+(model.x2-0.6)**2
model.f2 = (model.x1-0.85)**2+(model.x2-0.7)**2
model.f3 = (model.x1-0.9)**2+(model.x2-0.6)**2

with open('filename.txt', 'a') as f: #open and append members  a file in write mode
                            print(model.f1, model.f2, model.f3, sep = ' ', file=f)
def MHHM2(m):
    return 1/3*m.f1+1/3*m.f2+1/3*m.f3
model.obj = Objective(rule=MHHM2, sense=minimize)
#pyomo solve --solver=ipopt --summary --stream-solver MHH.py

**Comment by blnicho** [comment]
First, your Pyomo import statements are not correct. You should use **one** of the following `from pyomo.environ import *` or `import pyomo.environ as pyo`. The code snippets below assume you have used the first one.

I would recommend using `Expression` components to store `f1`, `f2`, and `f3`. For example:

```
model.f1 = Expression(expr=(model.x1-0.8)**2+(model.x2-0.6)**2)
model.f2 = Expression(expr=(model.x1-0.85)**2+(model.x2-0.7)**2)
model.f3 = Expression(expr=(model.x1-0.9)**2+(model.x2-0.6)**2)
```

I also recommend solving your model directly in the Python script instead of using the `pyomo solve` command using:
```
SolverFactory('ipopt').solve(model, tee=True)
```

Finally, after solving the model you can access the values of `f1`, `f2`, and `f3` using the `value` function:
```
print(value(model.f1))
```

I hope this helps. If you have additional implementation questions please direct them to the Pyomo forum or StackOverflow. Issues on the Pyomo GitHub page are meant for bug-reports and feature requests.

**Comment by chuongask** [comment]
Dear Blnicho,
Thank you very much for your message.
