### ISSUE TITLE
Can't put dual Suffix on Block?

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#1611]
In the following, the dual information is not actually imported:
```
from pyomo.environ import *

m = ConcreteModel()
m.b = Block()
m.x = Var(within=NonNegativeReals)
m.y = Var(within=NonNegativeReals)

m.obj = Objective(expr=m.x, sense=maximize)

m.b.cons = Constraint(expr=m.x + m.y <= 1)
m.b.dual = Suffix(direction=Suffix.IMPORT)

SolverFactory('gurobi').solve(m)

m.b.dual.pprint()
```
Obviously everything is fine if `m.b.dual` is instead `m.dual`.

Is this intentional? Can we support putting the dual Suffix wherever you want?

**Comment by ghackebeil** [comment]
It’s certainly known, and it’s not symmetric in that you can export suffix info from sub-blocks.

I suppose there is just ambiguity in where the imported suffix values can be stored. The top-level block is the easiest. One could consider the block that owns the component instead, there is a suffix there, falling back to the top-level block otherwise?

**Comment by ghackebeil** [comment]
Or walk up the parent block hierarchy until you find a suffix.

I think it could be done, just with a slight performance hit on solution loading.

**Comment by mrmundt** [comment]
The discussion on this topic has been consolidated into issue #2641.
