### ISSUE TITLE
[PEP] Public API for References

### ISSUE THREAD

**Issue by Robbybp** [Pyomo/pyomo#1640]
## Summary/Motivation
This PEP proposes the introduction of attributes and methods to distinguish and exploit components created via the `Reference` function. One reason for this is to avoid using references that may have been broken, e.g. by renaming of the underlying components (see #1571). Another is to avoid mistakenly doing something to the same component twice when iterating over `component_objects`. The only way I currently know to distinguish such components is by checking the type of their `_data` dict.

Some of the discussion on references in the past has been muddled by the fact that there are two (possibly more) distinct use cases for references:
i. To attach a component to a block other than its "home," without detaching it first.
ii. To create a "portable slice" of a component.

## Discussion
- Should the above use cases both be accomplished by the same function/objects, i.e. references? An alternative could be to have something like a SliceComponent.
- What methods or attributes should be added to Components (created via `Reference` or otherwise) to support distinction of references?

## Proposal
1. `Reference` continues to support both use cases mentioned above.
2. Add an `is_reference` method to `IndexedComponent`
3. Add a `referent` attribute to the object created by `Reference` that points to the component or slice used to construct it.

**Comment by blnicho** [comment]
Some comments from the dev meeting today:

- We need to be able to easily distinguish Reference components from the original components they are referencing. Ways to do this might involve using a different ctype for References, a utility function that is able to determine if a container component owns its data, or a method on IndexedComponent as suggested above.
- Could we make the writers Reference-aware to make sure we never send duplicate vars/constraints to a solver? Yes, there are ways to do this but they would likely involve caching and could have performance implications
- We need to be able to extract the "referent" from the Reference
- We need to be deliberate about what Pyomo "magic" we rely on when it comes to References because it can lead to weird or unexpected behavior when users don't fully understand the impact or side-effects of using References. Documentation of the expected use and behavior of References is also super important.

@carldlaird and @andrewlee94 your names came up as others who might have strong opinions on the design of References. Please add your thoughts and comments to this issue and we'll revisit this topic at our next Pyomo dev call.

**Comment by andrewlee94** [comment]
I have only run into one technical issue with `References` which relates to points 1.  I was writing some utility functions to count things like variables in a model, and I had to pass everything through a `ComponentSet` to filter out the duplicates caused by `References`.

So, my main comment on `References` is that I think they need to be easily distinguished from other component types, rather than appear as a duplicate object. I also agree that documentation is critical, and that users need to have a point of reference to learn about any of these technical issues (at the very least to prevent them coming to you with problems due to known limitation).

**Comment by blnicho** [comment]
Consolidating some relevant comments from previous issues/PRs:

### _Originally posted by @carldlaird  in  https://github.com/Pyomo/pyomo/issues/690_
We should have a design discussion about the aliasing feature "Reference". Some issues raised include:

- By default the created reference has the same ctype as the source - this means that the reference acts like the component (including, for example, that the data objects show up twice when we call component_data_objects)
- If the ctype is set to None, the issue above does not happen, however, the reference does not print when we print the model (so we don't know it exists)

Need to ensure we have correct behavior in use cases, and also clear output to the user that it exists and where it points.

One idea was to change the default ctype to "ComponentReference", but we need to think through the ramifications of adding a new ctype has on the transformations/writers.

### _Originally posted by @gseastream in https://github.com/Pyomo/pyomo/issues/690#issuecomment-423772538_

Just quick thoughts, but when discussing this feature I never imagined it would be an actual component. It made more sense to me that it's just its own object that has just enough methods and attributes to act like a real indexed component (so that ports can handle them correctly, for example). When it's its own component then you have the issue mentioned above where data objects show up twice. It's related to the issue we've always avoided of not letting components appear more than once on a block or on more than one block.

### _Originally posted by @jsiirola in https://github.com/Pyomo/pyomo/issues/909#issuecomment-475355019_

For good or ill, there is no such thing as a "Reference" object.  `Reference()` turns out to be a *function* that nominally returns a derivative of `IndexedComponent`.  If all the `_*Data`s referenced by the slice have the same ctype, then `Reference()` will return an instance of that ctype.  At that point, the only difference between the object returned from `Reference()` and a "normal" instance of that ctype is the type of the internal `_data` data structure: normal ctypes use `type(obj._data) is dict`, whereas the `Reference()` returns an object with `type(obj._data) is _ReferenceDict`.

If you don't want your references to be "indistinguishable" from normal components, you can pass your desired ctype to the call to `Reference()`.  The simplest thing is to use `Reference(..., ctype=None)`, which will return an instance of `IndexedComponent`.  You will lose some Component-level operators (like `pprint()`), but then the References will not be picked up by things like the `component_objects()` iterators.

**Comment by Robbybp** [comment]
@blnicho Thanks for posting, I hadn't seen that issue.

**Comment by Robbybp** [comment]
Closing this as #1740 has been merged.
