### ISSUE TITLE
References not cloned correctly

### ISSUE THREAD

**Issue by michaelbynum** [Pyomo/pyomo#1675]
This was the smallest problem I could put together to replicate the problem.

```
import pyomo.environ as pe

m = pe.ConcreteModel()
m.b = pe.Block([0])
m.b[0].x = pe.Var()
m.b.b = pe.Block()
m.b.b.x = pe.Reference(m.b[0].x)
print(m.b[0].x is m.b.b.x[None])  # True
m2 = m.clone()
print(m2.b[0].x is m2.b.b.x[None])  # False
```

**Comment by michaelbynum** [comment]
@jsiirola Any thoughts on this? This makes propagating values across arcs on cloned models quite difficult, which makes initialization for GDPopt subproblems difficult.

**Comment by jsiirola** [comment]
Not yet, but I will take a look at it.

**Comment by michaelbynum** [comment]
Thanks

**Comment by jsiirola** [comment]
This is a problem with your model and not with References:
```python
m.b = pe.Block([0])
m.b.b = pe.Block()
```
This is putting a Block on an IndexedBlock (i.e., as an attribute on the *container*),  As such, `m.b.b` isn't part of the Block hierarchy and doesn't have a proper `parent_block()` pointer.  Its contents won't be picked up by iterators like `component_objects()`, and it will not behave correctly when cloned: because it is not part of the Block hierarchy, `m.clone()` thinks that the block is outside the scope of the current model and thus does not clone it.  Note that:
```python
>>> m.b.b is m2.b.b
True
```

**Comment by michaelbynum** [comment]
Okay, here is the real model:

```
import pyomo.environ as pe
import idaes.core
import idaes.generic_models.unit_models
import idaes.generic_models.properties.swco2

m = pe.ConcreteModel()
m.fs = idaes.core.FlowsheetBlock()
m.fs.properties = idaes.generic_models.properties.swco2.SWCO2ParameterBlock()
m.fs.heater = idaes.generic_models.unit_models.Heater(default={'dynamic': False,
                                                               'property_package': m.fs.properties,
                                                               'has_pressure_change': True})
print(m.fs.heater.inlet.flow_mol[0] is m.fs.heater.control_volume.properties_in[0].flow_mol)  # True
m2 = m.clone()
print(m2.fs.heater.inlet.flow_mol[0] is m2.fs.heater.control_volume.properties_in[0].flow_mol)  # False
```

**Comment by michaelbynum** [comment]
Sorry about the previous example. My mistake. The extra block on the indexed block was a typo. When I thought that I had replicated the behavior, I copied and pasted without double checking my example.

**Comment by jsiirola** [comment]
OK - I finally dug into this.  The problem is not `Reference`, per se, but how an IDAES model uses references.  The problem is that an IDAES model uses a "dangling reference", effectively doing:
```python
m.fs.heater.inlet.add(Reference(m.fs.heater.control_volume.properties_in[:].flow_mol), 'flow_mol')
```
The problem with this is that the `IndexedComponent` returned by the reference has no context (that is, it has no `parent_component()`).  When `clone()` encounters and clones the `inlet` `Port`, it looks ar all the variables in the Port and clones them.  The catch is that `clone()` will only duplicate components that ate *in scope* (that is, contained in the block hierarchy rooted by the block that is being cloned).  As the `IndexedVar` in the Port has no parent, then it is out of scope and is not copied.

So, I am not sure what the "correct" solution would be.  I think the cleanest solution would be for an IDAES model to attach the reference to the model before adding it to the Port.  BUT, that might cause modeling components to be (potentially unexpectedly) picked up twice by the writers (at least until we resolve #1401).  I suppose a hack could be to attach the references to a deactivated block attached to the `Port.parent_component()`.  We could also "lie" and manually set the parent without attaching the object to the block (i.e., `m.fs.heater.inlet.flow_mol._parent = weakref.ref(m.fs.heater)`), but that seems worse / more dangerous (directly manipulating private attributes).

@andrewlee94: thoughts?

**Comment by andrewlee94** [comment]
@jsiirola My first thought was that the issue with apparently duplicating model components as you mentioned - @Robbybp in fact suggested at one point that we not attach any `References` to models. I think the reason in this case however was just to try to keep model size down by not attaching things to the model unless we really needed them.

So, I think resolving #1401 would make this a lot easy to work with, in that the duplicate component issue would disappear. Then we could attach these `References` somewhere and be done with this. The hacks are really just that, and adding a deactivated `Block` to a `Port` just to store the `References` seems like a big mess and overhead (and we have to think about what might happen if someone accidentally activates that `Block`?).

**Comment by Robbybp** [comment]
This looks like it is from the `add_port` method in `unit_model.py`. I think I insisted on using a "dangling reference" here because having references attached to models breaks the Pyomo scaling transformation (until #1596 gets merged, when you'll be able to circumvent the issue by not renaming). That said, we have other references attached to IDAES models, so it doesn't make a significant difference to keep this one unattached. My proposed fix would be to just attach this component back onto the model, although I'm not sure if this will break anything that relies on only encountering components once.

**Comment by michaelbynum** [comment]
This was resolved.
