### ISSUE TITLE
Error for Pyomo model viewer

### ISSUE THREAD

**Issue by sk2blue** [Pyomo/pyomo#1678]
Hi, 

Regarding Pyomo model viewer, I followed the advised instruction but it show some error as attached.
Could you please advise it?!

![Pyomo model viewer_input](https://user-images.githubusercontent.com/62978443/96843699-95216180-1489-11eb-83c3-8ee374997af2.JPG)
![Pyomo model viewer_output](https://user-images.githubusercontent.com/62978443/96843714-981c5200-1489-11eb-8eef-5281db089558.JPG)

**Comment by blnicho** [comment]
@eslickj is this an error you have seen before?

**Comment by eslickj** [comment]
I believe I have seen a similar error in Jupyter notebook.  Try to run "%gui qt" in it's own cell, and let if finish before running the rest.  I think the issue is that the subsequent commands execute before the QAppication finishes starting up.  You may think "%gui qt" would fully complete before returning, but that does not seem to be the case.

**Comment by sk2blue** [comment]
@eslickj @blnicho 
Thanks to your advise, it is well working now. The main problem was I should run "%gui qt" and let it finish before running the rest.
