### ISSUE TITLE
Using constant Params as an index

### ISSUE THREAD

**Issue by blnicho** [Pyomo/pyomo#17]
In the following code snippet, building the objective function fails because the get item function on an indexed component does not automatically replace a constant Param with its value. 

```
m.tf = Param(initialize=1)
m.t = ContinuousSet(bounds=(0,m.tf))
m.x = Var(m.t)

m.obj = Objective(expr=m.x[m.tf])
```

We could of course take the value of the parameter explicitly in the objective expression but this isn't as elegant and I think most users would expect the above code to work.

**Comment by ghackebeil** [comment]
The issue here is that an immutable singleton Param cannot replace itself with its own value. I suppose the model could do this when you access it, but then what is the point of keeping a Param object around anyway if you can't access it.

One possibility is to have all immutable Param objects be replaced with simple dictionaries or numeric values on the instance constructed by an AbstractModel. I like this because it leads to a nice trade off for abstract vs concrete modellers: Since immutable Params serve no purpose on ConcreteModel (maybe there is something I am forgetting though), Param declarations there could default to mutable; whereas on AbstractModel, Param declarations could default to immutable.

I'm not sure which type of model Bethany is using in the above example, but if it is AbstractModel, then it should lead to an error because the objective is not using a rule (m.x has not been constructed yet). If it is a ConcreteModel, there is no point in making m.tf a Param because it was not declared as mutable (just do m.tf = 1). With the changes I am proposing, if it was AbstractModel and the objective was fixed to use a rule, then the example would work. With a ConcreteModel, it would still be invalid to make m.tf a Param because it is used as an index (and the declaration would now create a mutable Param).

@jsiirola, @blnicho : What do you think about this? Maybe I am overthinking this and there is a one line "fix" to index component that would make this work.

**Comment by jsiirola** [comment]
I think there is a simple fix for this (I talked to Bethany & JP about it before asking her to submit the ticket):  I think we should change the `__getitem__` implementation in `IndexedComponent` (actually, I think it will be in `flatten_tuple`) so that any constant `_NumericValue` objects are evaluated to literals before generating the index.

I like this for a couple reasons: first, it does "the right [expected] thing"(tm) for immutable Params, but without relying on an `isinstance` call.  Second, in that logic we can generate meaningful errors for the case where non-constant things (mutable Params and Vars [fixed or free]) are passed as indexes. That is,
`model.var1[model.var2]`
can generate a meaningful error about indexing one variable by a non-constant thing (and in the case of a fixed value, a suggestion to wrap the index with a `value()` call)

**Comment by whart222** [comment]
That sounds like a good plan.

**Comment by bernalde** [comment]
This solves the issue. I think that it is not good to have several issues pointing to similar error, i.e. #17 and #340, therefore I will close this one. Thanks for the fix!
