### ISSUE TITLE
Resolve performance issue running BARON

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#179]
The key performance issue is that writing the file takes WAY too long relative to NL or LP files.

**Comment by ghackebeil** [comment]
There are two points worth considering in any discussion here:
 - There is an alternative interface to Baron through the NL writer. Unfortunately, "baronampl" (Baron for AMPL) is licensed separately from the Baron that takes .bar files, so a user might be stuck with one or the other depending how they purchased Baron.
 - The limiting model size that Baron can solve in a reasonable amount of time is likely not so large that performance of the .bar writer is an issue. I don't have any personal experience with this though.

**Comment by jsiirola** [comment]
I believe that this issue can be closed.  Since it was filed, the BAR writer was rewritten to use the walker logic introduced in pyomo5 expressions.  I spot-checked it using 
```
pyomo convert pmedian.py pmedian.test8.dat --output tmp.lp --report-timing
pyomo convert pmedian.py pmedian.test8.dat --output tmp.bar --report-timing
```
and the BAR writer was only 20% slower than the LP writer.  This is not to say that we shouldn't redesign the writers (we should: the current master takes nearly twice as long to write out the pmedian.test8 LP/BAR files as it took to initially generate the model), but that is a different issue.

If there is a specific model where this issue still applies, we can either re-open the issue with a reference to the example or else open a new issue.
