### ISSUE TITLE
How to set the 'NEOS_EMAIL' environment variable

### ISSUE THREAD

**Issue by ds2010** [Pyomo/pyomo#1817]
Hi all,

I encountered a problem with how to set the 'NEOS_EMAIL' environment variable.

 I understand that we can directly replace line 231 `email = os.environ.get('NEOS_EMAIL', '')` in [`kestrel.py`](https://github.com/Pyomo/pyomo/blob/master/pyomo/neos/kestrel.py) with `email = xxxx@xxx.xx`. 

But I would like to know whether it is possible to add the 'NEOS_EMAIL' environment variable in the model calculation script, something likes `solver_manager= SolverManagerFactory('neos', 'NEOS_EMAIL'=xxxx@xxx.xx')`  or ` results = solver_manager.solve(model, opt='minos',  'NEOS_EMAIL'=xxxx@xxx.xx')`.  So, could you please give me some suggestions? 

Many thanks in advance!

**Comment by jsiirola** [comment]
Due to the current structure of the solver / solver manager interfaces and the need to get a fix out quickly, we did not add anything to the solver / solver manager APIs for passing in the email.

Environment variables can be set at the system level outside of Python (the procedure varies by OS and can easily be found using Google), or within python you can set them with
```python
os.environ['NEOS_EMAIL'] = 'xxx@xxx.xxx'
```
