### ISSUE TITLE
Expression objects do not support inplace operators

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#1890]
The following:
```python
m = ConcreteModel()
m.x = Var()
m.y = Var()
m.e = Expression(expr=m.x)
m.e += m.y
```
produces a self-referential Expression:
```python
>>> type(m.e.expr)
<class 'pyomo.core.expr.numeric_expr.SumExpression'>
>>> print([str(_) for _ in m.e.expr.args])
['e', 'y']
```

**Comment by ghackebeil** [comment]
I recall attempting to disable the in-place operators when I first added Expression, but ran into issue getting magic reference count stuff that triggers cloning to work correctly in certain cases. Perhaps that is no longer an issue, or I just got it wrong. Or maybe I was trying to redirect them to the inner expression.

I’m okay with disabling the operators for the expression object itself, if you think that makes sense.

**Comment by jsiirola** [comment]
Personally, I think we should support something like `m.e += m.x`: it is useful in iterative algorithms when you want to augment, e.g., an objective.  Note that the following *does* work correctly:
```python
m.e.expr += m.x
```
If we chose to remove support for `m.e += `, it needs to generate a reasonable error redirecting users to `m.e.expr += `. 

I am mostly filing this so that I remember the issue when we get around to making another pass at cleaning up / refining the expression system.

**Comment by michaelbynum** [comment]
I would have expected `m.e += m.x` to do `m.e.expr += m.x` under the hood.

**Comment by ghackebeil** [comment]
I just remembered, there is some ambiguity here that is problematic. Consider this common scenario:
```python
tmp = <starting-expression>
for i in ...:
   tmp += ...
```
It is very easy to write `<starting-expression>` in a way that might simplify down to a single named `Expression` (e.g., `immutable_param[j] + m.named_expression`, where `immutable_param[j] = 0`). Thus, just consider the trivial case:
```
m.e = Expression()

tmp = m.e
for i in ...:
    tmp += ...
```
We can't always assume a user's intention is to modify the internal expression. The in-place operators might be used as part of building an external expression. Also, the internal expression might not be assigned anything yet, which is okay because it is a placeholder. The loop behavior above should be the same whether the starting `tmp` is a Var, Expression, Param, or constant.
