### ISSUE TITLE
Constraints rebuilt only for missing points after discretization

### ISSUE THREAD

**Issue by vova292** [Pyomo/pyomo#1955]
## Summary

Constraints indexed by a continuous set are constructed at the time of model construction. This will build constraints for the elements already existing in the continuous set. After discretization the constraints rule is called for the new points added to the continuous set

If the constraint rule for example works on a variable at the current value from the set and the previous value then the user would expect it be rebuilt based on the discrete points in the set. But that is not what happens

The following is an example of a constraint rule that would not behave as expected by the user
```
        def _con_rule(mod, i):
            if i == 0:
                return pyo.Constraint.Skip
            else:
                return mod.constant * mod.dy[i]  == -mod.gain * (mod.y_hor[i] - mod.y_hor[mod.time.prev(i)]) 

```

**Comment by blnicho** [comment]
This is expected and intentional behavior. Your example appears to be a discretized differential equation and would be better implemented as a differential equation (that pyomo.dae would then discretize for you). Constraints indexed by ContinuousSets will be generated using the discretization points contained in the ContinuousSet at the time the constraint was constructed and existing constraints (corresponding to points that were already in the ContinuousSet) will not be updated if additional points are added to the ContinuousSet during discretization (new constraints will only be generated for the new discretization points). 

I know of very few cases where using the `prev` and `next` methods makes sense in the context of a pyomo.dae model so please double check your formulation to make sure your model is well-posed. If you do need to use `prev` or `next` in a constraint you just have to make sure the constraint is added after the model has been fully discretized.
