### ISSUE TITLE
CI Failing due to Ipopt install

### ISSUE THREAD

**Issue by michaelbynum** [Pyomo/pyomo#1962]
GHA tests are failing because the installation of ipopt from idaes-ext is failing. I was going to create a PR to use a fixed version of idaes-ext, but I wanted to see if anyone had other ideas. Is there a reason we need to use the latest release of idaes-ext for our tests?

**Comment by jsiirola** [comment]
It is convenient to use the most recent release, as that is updated relatively frequently with new tools / builds that we are starting to leverage (like `k_aug`, and hopefully in the near future, cyipopt).  The problem is that the most recent release is broken (the artifacts didn't build).  I am working with @eslickj on that at the moment.

If we need to update the GHA workflows right now, I would prefer a patch that finds the most recent release that has artifacts, OR that we support a "black list" of releases that we never want to use.

**Comment by jsiirola** [comment]
FYI: something like the following would work:
```diff
diff --git a/.github/workflows/test_pr_and_main.yml b/.github/workflows/test_pr_and_main.yml
index e0283d7..a94a73f 100644
--- a/.github/workflows/test_pr_and_main.yml
+++ b/.github/workflows/test_pr_and_main.yml
@@ -319,8 +319,13 @@ jobs:
                 exit 0
             fi
             URL=https://github.com/IDAES/idaes-ext
-            RELEASE=$(curl --max-time 150 --retry 8 \
-                -L -s -H 'Accept: application/json' ${URL}/releases/latest)
+            TARGET=idaes-solvers-ubuntu1804-64.tar.gz
+            RELEASE=$(curl --max-time 150 --retry 8 -L -s \
+                -H "Accept: application/vnd.github.v3+json" \
+                https://api.github.com/repos/IDAES/idaes-ext/releases \
+                | python -c "import json, sys; \
+                print(list(rel['tag_name'] for rel in json.load(sys.stdin) \
+                if any(a['name'] == '$TARGET' for a in rel['assets']))[0])")
             VER=$(echo $RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
             URL=${URL}/releases/download/$VER
             if test "${{matrix.TARGET}}" == linux; then
```
The only problem is that it hits the (anonymous) github API, which has a pretty low rate limit before queries start to fail.

**Comment by eslickj** [comment]
I deleted the empty release.  I'll also be sure not to create an empty release in the future.  Or course it's always possible new releases will have unforeseen issues.

**Comment by mrmundt** [comment]
@eslickj resolved this issue, so this can be closed.
