### ISSUE TITLE
Error while executing a MILNP example from the documentation

### ISSUE THREAD

**Issue by damianoazzolini** [Pyomo/pyomo#1978]
## Summary
I'm following https://pyomo.readthedocs.io/en/stable/contributed_packages/mindtpy.html

### Steps to reproduce the issue

```python
Required imports
>>> from pyomo.environ import *

Create a simple model
>>> model = ConcreteModel()

>>> model.x = Var(bounds=(1.0,10.0),initialize=5.0)
>>> model.y = Var(within=Binary)

>>> model.c1 = Constraint(expr=(model.x-4.0)**2 - model.x <= 50.0*(1-model.y))
>>> model.c2 = Constraint(expr=model.x*log(model.x)+5.0 <= 50.0*(model.y))

>>> model.objective = Objective(expr=model.x, sense=minimize)

Solve the model using MindtPy
>>> SolverFactory('mindtpy').solve(model, mip_solver='glpk', nlp_solver='ipopt') 
...
```

### Error Message

```console
>>> SolverFactory('mindtpy').solve(model, mip_solver='glpk', nlp_solver='ipopt')
WARNING: Loading a SolverResults object with a warning status into
    model.name="unknown";
      - termination condition: other
      - message from solver: <undefined>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/usr/.local/lib/python3.7/site-packages/pyomo/contrib/mindtpy/MindtPy.py", line 247, in solve
    MindtPy_initialize_master(solve_data, config)
  File "/home/usr/.local/lib/python3.7/site-packages/pyomo/contrib/mindtpy/initialization.py", line 87, in MindtPy_initialize_master
    init_rNLP(solve_data, config)
  File "/home/usr/.local/lib/python3.7/site-packages/pyomo/contrib/mindtpy/initialization.py", line 175, in init_rNLP
    (subprob_terminate_cond, results.solver.message))
ValueError: MindtPy unable to handle relaxed NLP termination condition of other. Solver message: <undefined>
```

### Information on your system

Pyomo version: Pyomo 5.7.3 (CPython 3.7.10 on Linux 4.4.0-19041-Microsoft)
Python version: Python 3.7.10
Operating system: WSL in windows
How Pyomo was installed (PyPI, conda, source): pip
Solver (if applicable): ipopt

**Comment by ZedongPeng** [comment]
I am using macOS and this error doesn't happen in my environment. In MindtPy, the default initialization strategy is `rNLP`.

According to your output, IPOPT failed to solve the continuous relaxation of your MINLP model and the initialization process failed. I would suggest you look into the log file of IPOPT and find the reason why IPOPT failed.

I will add the code to handle the `other` termination condition in initialization. Hopefully, it will be merge in #1847 .

Btw, if you want to solve this issue before the RP is merged, you can try another NLP solver instead of IPOPT, or use a different initialization strategy, like `max_binary` or `initial_binary`.
