### ISSUE TITLE
is_parameter_type() method: IndexedParam is not a parameter

### ISSUE THREAD

**Issue by QuriousCube** [Pyomo/pyomo#2032]
## Summary

I want to test if a thing in the model is a parameter. When the thing is an `IndexedParam`, its `is_parameter_type()` method returns False.

### Steps to reproduce the issue

```console
$ conda install -c conda-forge pyomo
$ python3 test.py
```

```
# test.py
import pyomo.environ as pyo
import numpy as np

ix_set = pyo.RangeSet(2)
p_init = np.array([0, 1])
def init_workaround(model, i):
    return p_init[i - 1]
p = pyo.Param(ix_set, initialize=init_workaround)
print(type(p))
assert p.is_parameter_type()
```

### Error Message

```console
<class 'pyomo.core.base.param.IndexedParam'>
Traceback (most recent call last):
  File "<...>/test.py", line 10, in <module>
    assert p.is_parameter_type()
AssertionError
```

### Information on your system

Pyomo version: 6.0.1
Python version: 3.9.5
Operating system: Fedora 33
How Pyomo was installed (PyPI, conda, source): conda-forge
Solver (if applicable): not applicable

**Comment by jsiirola** [comment]
This is intentional behavior.  An IndexedParam is not itself a "parameter", but rather a container that holds parameters (the `is_*_type()` queries are intended to be fast methods for working with expression trees, and the containers are not designed to appear directly in expressions).

A test that does what you (probably) want is to test `if p.ctype is Param`.
