### ISSUE TITLE
IPOPT solver call time issue.

### ISSUE THREAD

**Issue by mkrun** [Pyomo/pyomo#208]
Hi,

Following up from my issue on [stackoverflow](https://stackoverflow.com/questions/45873846/pyomo-takes-time-after-ipopt-solver-call/45883032?noredirect=1#comment78750415_45883032), qtothec mentioned that there might be some ongoing development for transfering the model information to IPOPT without writing a file to disk by going through CasADi. 

Can you throw some light into this topic?

**Comment by jsiirola** [comment]
As @qtothec mentioned, a direct memory interface for ipopt is something that has been discussed; however, no definitive has been started.  Several of us have interest in improving the efficiency of the NL toolchain, and it is possible that something may happen in the next 3-6 months.

It would be very helpful if you can contribute your model to the development team so that we can use it for benchmarking and profiling.
