### ISSUE TITLE
Install Ipopt solver to use with Pyomo in ubuntu

### ISSUE THREAD

**Issue by spartakos87** [Pyomo/pyomo#224]
How can I install ipopt solver to use it with pyomo in ubuntu??? I have already download the zip file of [ipopt](http://ampl.com/products/solvers/open-source/)

but I don'n find any specific instructions how to install it and use it with pyomo.

**Comment by qtothec** [comment]
If you downloaded the executable, just unzip it onto the system path. If you downloaded the source code, you'll have to run the commands to build it from source, then add it to your system path. I would have a look at the ipopt installation instructions. This isn't so much a Pyomo issue, because installing ipopt for Pyomo is roughly the same as installing ipopt itself.

**Comment by spartakos87** [comment]
My issue is where to put the executable ipopt in pyomo , in which folder.

**Comment by qtothec** [comment]
Type "echo $PATH" into your terminal. You can put IPOPT into any of those directories. Or you can add the IPOPT directory to your path.
