### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'tuple'

### ISSUE THREAD

**Issue by ashishpatel26** [Pyomo/pyomo#2241]
```bash 
PS D:\vscode\OptiimizationMethods> & C:/Users/SHIVA/miniconda3/envs/mlops/python.exe d:/vscode/OptiimizationMethods/LinearProgramming/pyomo_code.py 
```
**This is error region**

```bash
Traceback (most recent call last):
  File "d:/vscode/OptiimizationMethods/LinearProgramming/pyomo_code.py", line 20, in <module>
    opt.solve(model)
  File "C:\Users\SHIVA\miniconda3\envs\mlops\lib\site-packages\pyomo\opt\base\solvers.py", line 601, in solve
    result = self._postsolve()
  File "C:\Users\SHIVA\miniconda3\envs\mlops\lib\site-packages\pyomo\solvers\plugins\solvers\CBCplugin.py", line 898, in _postsolve
    results = super(CBCSHELL, self)._postsolve()
  File "C:\Users\SHIVA\miniconda3\envs\mlops\lib\site-packages\pyomo\opt\solver\shellcmd.py", line 277, in _postsolve
    results = self.process_output(self._rc)
  File "C:\Users\SHIVA\miniconda3\envs\mlops\lib\site-packages\pyomo\opt\solver\shellcmd.py", line 350, in process_output
    results = self.process_logfile()
  File "C:\Users\SHIVA\miniconda3\envs\mlops\lib\site-packages\pyomo\solvers\plugins\solvers\CBCplugin.py", line 668, in process_logfile
    if self.version() < (2, 10, 2):
TypeError: '<' not supported between instances of 'NoneType' and 'tuple'
```

**Comment by jsiirola** [comment]
What version of CBC are you using?

**Comment by ashishpatel26** [comment]
Latest one

**Comment by jsiirola** [comment]
What do you get when running `cbc -quit` on the command line?

**Comment by AyrtonB** [comment]
Hi @jsiirola and @ashishpatel26, I'm reaching the exact same error. When I run `cbc -quit` I get:

```bash
Welcome to the CBC MILP Solver
  Version: 2.9.7
  Build Date: Oct 10 2015
  Revision Number: 2226
```

**Comment by jsiirola** [comment]
So the error is coming from failing to parse the CBC version.  This is something that is tested as part of the normal Pyomo build tests, and we are not seeing the error. 

@AyrtonB, are you also running on Windows?

I wonder if this is an issue because you are running with a different (non-en_US) locale? Alternatively, it is possible that Pyomo is finding a different “cbc” executable that is not returning a meaningful version string. 

If you are willing to help debug, it would be helpful if you could edit `pyomo/solvers/plugins/solvers/CBCplugin.py` and add `print(“VER STRING:”, results.stdout)` before line 57 (immediately above `_cbc_version = _extract_version(results.stdout)`), and then post what gets printed.

**Comment by KarolGongolaVirtusLab** [comment]
Hi, I had the same error because I cannot add this executable file location to PATH. 

I use: `pyomo.SolverFactory('cbc', executable="path_to_cbc")`

but for collecting version there is hardcoded cmd:
line 50 in CBCplugin.py: `executable = Executable("cbc")`

**Comment by KarolGongolaVirtusLab** [comment]
So my workaround is:
```
solver = pyomo.SolverFactory('cbc', executable='path_to_cbc')
results = subprocess.run([solver._user_executable, "-stop"], timeout=1,
                                             stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                             universal_newlines=True)
solver._version = _extract_version(results.stdout)
```
