### ISSUE TITLE
gdp.fix_disjuncts assumes all Disjuncts are set and doesn't die very gracefully if they aren't

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#2261]
## Summary

This is issue is mainly a question, which is: Should the `gdp.fix_disjuncts` transformation be a transformation from a GDP to a MI(N)LP? Historically, this seems to have been assumed: at least in `gdpopt`, after `fix_disjuncts` is called, it is assumed that the NLP subproblem can be solved with a MI(N)LP solver. The alternative would be for it to support `Disjunction` targets, in which case it should complain if not all the Disjuncts' indicator_vars in the Disjunction are set, but it could leave unspecified Disjunctions alone. In the first case, I think it would have a responsibility to transform logical stuff on the model. In the second case, probably not. In either case, it needs an error message that tells the user something more informative than the `ValueError` below.

### Steps to reproduce the issue

```
from pyomo.environ import *
from pyomo.gdp import *

m = ConcreteModel()
m.d1 = Disjunct()
m.d2 = Disjunct()
m.d = Disjunction(expr=[m.d1, m.d2])
m.another1 = Disjunct()
m.another2 = Disjunct()
m.another = Disjunction(expr=[m.another1, m.another2])

m.d1.indicator_var.set_value(True)
m.d2.indicator_var.set_value(False)
        
TransformationFactory('gdp.fix_disjuncts').apply_to(m)
```

### Error Message

```
ERROR: evaluating object as numeric value: another1.binary_indicator_var
        (object: <class 'pyomo.gdp.disjunct.AutoLinkedBinaryVar'>)
    No value for uninitialized NumericValue object
    another1.binary_indicator_var
Traceback (most recent call last):
  File "partially_fixed.py", line 15, in <module>
    TransformationFactory('gdp.fix_disjuncts').apply_to(m)
  File "/home/esjohn/src/pyomo/pyomo/core/base/transformation.py", line 69, in apply_to
    self._apply_to(model, **kwds)
  File "/home/esjohn/src/pyomo/pyomo/gdp/plugins/fix_disjuncts.py", line 49, in _apply_to
    self._transformContainer(model)
  File "/home/esjohn/src/pyomo/pyomo/gdp/plugins/fix_disjuncts.py", line 66, in _transformContainer
    if fabs(value(_binary) - 1) <= self.config.integer_tolerance:
  File "/home/esjohn/src/pyomo/pyomo/core/expr/numvalue.py", line 143, in value
    raise ValueError(
ValueError: No value for uninitialized NumericValue object another1.binary_indicator_var
```

### Information on your system

Pyomo version: main
Python version: 3.8
Operating system: centos7
How Pyomo was installed (PyPI, conda, source): source
Solver (if applicable):

**Comment by emma58** [comment]
Unless someone has an inspiring use case for supporting targets here, I think I would be for it being a promise of going to a MI(N)LP, which means adding a call to `core.logical_to_linear` after the Disjuncts have been reclassified.

**Comment by bernalde** [comment]
I agree that fixing the disjunct should return a (MI)NLP problem. I use the parenthesis around (MI). For the traditional GDPs, only the Boolean variables end up representing discrete choices but nothing (practically, theoretically, we still need to talk about this) from putting discrete variables in the disjunctions. Since not all logical variables might be directly fixed, I would certainly support calling `core.logical_to_linear` afterward. We recently had to write our work-around for another project (https://github.com/bernalde/dsda-gdp).
Finally, I do not see any case where someone would call `gdp.fix_disjuncts` to perform just a partial fixing and end with a different GDP problem. It would be a nice generalization of this method, where the default is fixing all the Boolean variables. This raises the issue, what happens with the Disjuncts without any value assigned to them? This should be relevant for GDPOpt and the initial_disjunct initialization procedure.

**Comment by emma58** [comment]
@bernalde, thank you for the response! And good point about the (MI) part.

I think we shouldn't support fixing the non-indicator_var BooleanVars unless we have a need, though I agree that one could definitely want to do such a thing: For example if you were doing an enumeration algorithm to solve a GDP which had non-indicator_var booleans, you may as well enumerate over those too. However, even in that case, I'm not at all convinced that it's the job of the `fix_disjuncts` transformation to fix those.

And to answer your question, I would propose that the transformation raise an error for Disjuncts without any value assigned to them. If it is a promise to go to a (MI)NLP, then that is a case that it cannot handle, so it should just complain. Right now it dies the ugly death above, so this isn't really a change in behavior.
