### ISSUE TITLE
Support cython function to initialize set

### ISSUE THREAD

**Issue by bertrandhaut** [Pyomo/pyomo#2374]
## Summary

Currently it's impossible to pass a "cython" function to initialize a Set. 

The point is that, in the "Initializer" function of pyomo.core.base.util, the cython function is not correctly recognized and a "ConstantInitializer" is returned. Ideally a "ScalarCallInitializer" or "IndexedCallInitializer" should be returned. 

It would be nice to support passing "cython" function.

### Rationale
The main reason to support cython function is that there is no good reason to not accept them. They are behaving mostly like normal python function.

 In particular I think that the only modification needed will be in the Initializer function of pyomo.core.base.util.

Pyomo is currently relying on "inspect.isfunction" which does not recognized cython function. Note that other methods of "inspect" such as "inspect.getfullargspec(init)" and "inspect.ismethod(init)" are working correctly on cython function.

### Description

There are many discussions around the question whether "inspect.isfunction" should return true or false for cython function. It seems that it will not change soon. The reason is that cython function are not supporting ALL the features expected from types.FunctionType. But these features are not needed by pyomo. 

As workaround in my code I'm currently using the following patching:

```
from unittest.mock import patch

def extended_isfunction(f):
    return isinstance(f, types.FunctionType) or (type(f).__name__ == 'cython_function_or_method')

with patch('inspect.isfunction', new=extended_isfunction):
    my_pyomo_code
```
It would be nicer if this logic could be implemented in pyomo directly.

**Comment by wrcannon** [comment]
Is this possibly related to the issue that I am having with pyomo and cython: https://stackoverflow.com/questions/71902579/pyomo-doesnt-load-when-called-via-cython.
This too seems to be an initialization issue.

**Comment by jsiirola** [comment]
This issue is unrelated to the linked SO question (The linked question is probably either a problem with how the pyomo driver script interacts with argparse [it really shouldn't be doing that much when pyomo.environ is imported - that is almost certainly a bug], or with how cython and argparse interact).

@bertrandhaut, I think your proposed solution is a reasonable starting point, although I find it troublesome that we would need to hack around a standard module (`inspect`) to support cython.  This really feels like a fundamental problem with cython.

I believe that there is a simpler workaround, as well.  You should be able to explicitly create the desired `ScalarCallInitializer` or `IndexedCallInitializer`, i.e.
```python
from pyomo.core.base.initializer import ScalarCallInitializer
# ...
model.I = pyo.Set(initialize=ScalarCallInitializer(my_cython_fcn))
# or
model.J = pyo.Set(model.I, initialize=IndexedCallInitializer(my_indexed_cython_fcn))
```

**Comment by wrcannon** [comment]
@[jsiirola](https://github.com/jsiirola), Thanks I will enter a ticket for this as a bug.
