### ISSUE TITLE
GAMS writer fails for power nested in a log

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#244]
The functionality to selectively replace `**` with `power()` fails in an edge case when `**` is nested within a `log` function, e.g. `log(x ** 2)`. In `replace_power()`, the `assert` that `arg` is bound by `(` and `)` fails because the arg is bound by `log(` and `)`. This is possibly also true with other similar functions, e.g. `exp()`.

@gseastream

**Comment by whart222** [comment]
The changes included in PR #272 address this issue on the expr_dev branch.

**Comment by qtothec** [comment]
I'm not sure it's good practice to close issues before their associated PR is merged. Github supports automatic closing of linked issues: https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by whart222** [comment]
The issue here is that code change on another branch resolved the issue.
John argued that we should re-open and accept this PR, since it's a minor
change that will impact users soon.

But in general there isn't a standard way to address the situation that we
have, where conflicting changes are happening on separate branches.  I
think it's OK to close a PR like this to avoid duplicating work.

**Comment by qtothec** [comment]
Huh? I think that I'm a bit confused here because I agree with what you say about conflicting PR's, but this is an issue, not a PR.
