### ISSUE TITLE
Appropriate behavior for nested Disjunct

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#254]
While handling of nested Disjunctions makes sense, it is currently unclear how nested Disjuncts should act with respect to activation/deactivation.

```
m = ConcreteModel()
m.x = Var(bounds=(0, 2))
m.d1 = Disjunct()
m.d1.c = Constraint(expr=m.x >= 1)
m.d2 = Disjunct()
m.d2.c = Constraint(expr=m.x >= 1.1)
m.d3 = Disjunct()
m.d3.c = Constraint(expr=m.x >= 1.2)
m.d4 = Disjunct()
m.d4.c = Constraint(expr=m.x >= 1.3)
m.disj = Disjunction(expr=[m.d1, m.d2])
m.d1.disj = Disjunction(expr=[m.d3, m.d4])
```
Here, `m.d1` being inactive relaxes the `m.d1.disj` disjunction. If, however, the model is written:
```
m = ConcreteModel()
m.x = Var(bounds=(0, 2))
m.d1 = Disjunct()
m.d1.c = Constraint(expr=m.x >= 1)
m.d2 = Disjunct()
m.d2.c = Constraint(expr=m.x >= 1.1)
m.d1.d3 = Disjunct()
m.d3.c = Constraint(expr=m.x >= 1.2)
m.d1.d4 = Disjunct()
m.d4.c = Constraint(expr=m.x >= 1.3)
m.disj = Disjunction(expr=[m.d1, m.d2])
m.disj2 = Disjunction(expr=[m.d1.d3, m.d1.d4])
```
When `m.d1` is inactive here, it does not seem appropriate to me for `m.d3` and `m.d4` to be deactivated as well. Therefore, I propose that canonical behavior for Disjunct deactivation (`indicator_var = 0`) to not correspond to deactivation of the Disjunct as a container.

**Comment by emma58** [comment]
Where does this not do what you expect? I agree with your proposal, but I think that is how it works (or should work). In the first case, the disjunction lives in the disjunct, so its XOR constraint is in `m.d1`, which means it is relaxed when `m.d1` is deactivated. In the second case, I assume you mean to have the constraints on `m.d1.d3` and `m.d1.d4`, and that you want those to still be active after `m.d1` is deactivated, right? And in that case, I think it should be fine because the disjunction is on the model. Neither `m.d1.d3.indicator_var` nor `m.d1.d4.indicator_var` are fixed to 0 when `m.d1` is deactivated, and the XOR constraint is on the model, so it will also still be enforced. I just tried your example with bigm and `m.disj2` was enforced. But maybe things aren't as pretty in other transformations?

**Comment by qtothec** [comment]
No assignment of blame. I wanted to make this conversation public and explicit somewhere, because I was working on the fix-disjuncts transformation, and it came up as a potential pitfall in my mind.

**Comment by emma58** [comment]
Yes--It's a good thought. And it will make a good test!
