### ISSUE TITLE
Wrong transformation results with gdp.hull and gdp.mbigm

### ISSUE THREAD

**Issue by BentzJoerg** [Pyomo/pyomo#2702]
## Summary
I am working on MINLPs and are using the GDP-toolbox of pyomo. While trying to nest some disjunctions I encountered a wrong behaviour of gdp.hull which is providing wrong results. Further the gdp.mbigm was not working on the specific problem I tried. I am well aware, that mbigm is not supporting nested GDPs, but in that state of the model die Disjunctions I made were not actually nested.

### Steps to reproduce the issue
```
# example.py
import pyomo.environ as pyo
import pyomo.gdp as pogdp

model = pyo.ConcreteModel()
model.T = pyo.RangeSet(10)
model.x=pyo.Var(model.T,bounds=(1, 10))
model.y=pyo.Var(model.T,bounds=(1, 100))

def _op_mode_sub(m, t):
    m.disj1[t].c1= pyo.Constraint(expr=m.x[t] == 2) 
    m.disj1[t].sub1 = pogdp.Disjunct()
    m.disj1[t].sub1.c1= pyo.Constraint(expr=m.y[t] == 100)
    m.disj1[t].sub2 = pogdp.Disjunct()
    m.disj1[t].sub2.c1= pyo.Constraint(expr=m.y[t] == 1000)
    return [m.disj1[t].sub1, m.disj1[t].sub2]

def _op_mode(m, t):
    m.disj2[t].c1= pyo.Constraint(expr=m.y[t] == 10)
    return [m.disj1[t], m.disj2[t]]

model.disj1 = pogdp.Disjunct(model.T)
model.disj2 = pogdp.Disjunct(model.T)
model.disjunction1sub = pogdp.Disjunction(model.T, rule=_op_mode_sub)
model.disjunction1 = pogdp.Disjunction(model.T, rule=_op_mode)

def obj_rule(m, t):
    return pyo.quicksum(pyo.quicksum([m.x[t] + m.y[t]], linear=False) for t in m.T)
model.obj = pyo.Objective(rule=obj_rule)

gdp_relax=pyo.TransformationFactory('gdp.bigm').apply_to(model)
#pyo.TransformationFactory('gdp.hull').apply_to(model)
#gdp_relax=pyo.TransformationFactory('gdp.mbigm').apply_to(model)

pyo.SolverFactory('glpk').solve(model)
print(pyo.value(model.obj))
```
### Results
using gdp.bigm: obj=110.0 "right result"
using gdp.hull: obj=1020.0 "wrong result"
using gdp.mbigm:  "error"

### Error Message
```console
$ #RuntimeError: Cannot add component 'transformed_bound_constraints_index' (type <class 'pyomo.core.base.set.SetProduct_InfiniteSet'>) to block '_pyomo_gdp_mbigm_reformulation': a component by that name (type <class 'pyomo.core.base.set.SetProduct_InfiniteSet'>) is already defined.
```

### Information on your system
Pyomo version: 6.4.4
Python version: 3.9.15
Operating system: Windows 10
How Pyomo was installed (PyPI, conda, source): conda
Solver (if applicable): glpk / baron

**Comment by emma58** [comment]
@BentzJoerg, thank you for submitting this! 

(In notes to future me), I think this is a bug (in 'bigm' at least) where the transformation is putting the transformed disjunctive constraints on the parent block of the Disjunct rather than the Disjunction. This is causing them to get double-transformed, creating nested behavior in a not-nested model.

**Comment by emma58** [comment]
Note that it is actually `hull` that is right in this case. The model is not in fact nested since in Pyomo we define the GDP hierarchy based on where Disjunc*tions* are declared, not Disjuncts. This means that this model encodes the math:
![image](https://github.com/Pyomo/pyomo/assets/12833636/ce771fb6-a4bc-4c37-b44c-2b8af964458c)
So the optimal value of 1020 is in fact correct. @BentzJoerg, if you were intending a nested model, then you should declare `disjunction1sub[t]` on `disj1[t]`, for each t. This is I think what you were expecting if you anticipated an optimal value of 110.
