### ISSUE TITLE
NL_v2 no symbolic solver labels for named expressions

### ISSUE THREAD

**Issue by bknueven** [Pyomo/pyomo#2793]
## Summary
NL_v2 does not pass names of named Expressions to the solver when using `symbolic_solver_labels = True`.

### Steps to reproduce the issue

```python
from pyomo.environ import *                                                                                                                                                                                                 

m = ConcreteModel()
m.x = Var(initialize=-1)
m.my_expression = Expression( expr = m.x**0.5 )

m.my_constraint = Constraint( expr = m.my_expression == 0 ) 

s = SolverFactory("ipopt")
s.options["halt_on_ampl_error"] = "yes"

s.solve(m, tee=True, symbolic_solver_labels=True)
```

### Error Message

When NL_v1, the message returned by Ipopt is:
```console
Error evaluating constraint my_constraint: can't evaluate pow(-1,0.5).
```

With NL_v2 I get the less helpful message below:
```console
Error evaluating "var =" definition 1: can't evaluate pow(-1,0.5).
```

### Information on your system

Pyomo version: 6.5.1.dev0 (a6446ae)
Python version: 3.10.9
Operating system: macOS x86_64
How Pyomo was installed (PyPI, conda, source): source
Solver (if applicable): Ipopt

**Comment by jsiirola** [comment]
One of the performance improvements in the NLv2 writer is that named expressions are now emitted to the NL file as AMPL "defined variables".  This provides significant benefits, especially in the case where the same named expression appears in several expressions.  The downside is that there does not appear to be any way to pass the name of the defined variable to the ASL so that it includes it in the error message (simply appending additional names to the COL file does *not* work).

You can recover the old NLv2 behavior by turning off the export of "defined variables":
```python
s.solve(m, tee=True, symbolic_solver_labels=True, export_defined_variables=False)
```

**Comment by bknueven** [comment]
Thanks for the explanation @jsiirola.
