### ISSUE TITLE
Gurobi 10.0 support

### ISSUE THREAD

**Issue by tcplusplus** [Pyomo/pyomo#2872]
## Summary

Gurobipy 10.x support

### Rationale

I have been using pyomo with gurobipy 9.5.2 for some time in python 3.9. I am look into updating the project to python 3.11, but only the gurobipy 10.x is supported on python 3.11

### Additional information

If I run the code now I get the error
pyomo.common.errors.ApplicationError: Could not create Model for <class 'pyomo.solvers.plugins.solvers.gurobi_direct.GurobiDirect'> solver plugin - gurobi message=Could not create Model - gurobi message=No compatible runtime available for version 10.0.2

**Comment by blnicho** [comment]
@tcplusplus could you clarify what enhancement you're requesting here? Pyomo already supports and is tested against Python 3.11 and gurobipy 10.0.2.

**Comment by simonbowly** [comment]
@tcplusplus the underlying error here is coming from gurobipy. It occurs because you are connecting to a Gurobi compute server which has not been updated to version 10.0.2 on the server side.

See more details here: https://support.gurobi.com/hc/en-us/articles/360026621732-How-do-I-resolve-the-error-No-compatible-runtime-available-for-version-X-X-X
