### ISSUE TITLE
Find unfixed variables in active constraints

### ISSUE THREAD

**Issue by eslickj** [Pyomo/pyomo#291]
It would be nice to be able to easily count unfixed variables in active equality constraints.  This would help with things like calculating the degrees of freedom. Going farther it would also be nice to have an incidence matrix of variables in constraints.  This could help with lots of stuff like initialization, decomposition, determining if Blocks are independent...

Here is my current attempt at counting: https://github.com/IDAES/models/blob/master/idaes_models/ui/report.py#L111. I think an incidence matrix is a pretty straight forward extension, but both counting and making an incidence matrix are pretty inefficient tasks as far as I can tell.

**Comment by qtothec** [comment]
I think that this would be a great contribution to the diagnostic functions being developed. Relevant issue is #211 and PR at #217.

**Comment by whart222** [comment]
This capability already exists in Pyomo.  Given an expression object *expr*, you can call the identify_variables(expr, include_fixed=False) function, which returns variable objects that aren't fixed.

We don't have a utility function to do this for all constraints/objectives in a model, but I'm not sure that's warranted since you can easily iterate over all objectives and constraints and collect this information.

**Comment by carldlaird** [comment]
This seems exactly what "utility functions" are for. I agree that users can write the loops today, but having utility functions for some of these tasks will prevent the copy-paste-12-lines-of-code syndrome.

The Pyomo team needs to have some discussion about what goes into core Pyomo vs what we would expect users to keep in their code. The bar for this decision is not just whether or not the code is general - we don't want to blindly grow the code base, because it all has to be supported and maintained moving forward.

Baring a formal decision, maybe the right mechanism is to have a spot for these kind of utility functions inside of contrib?

**Comment by whart222** [comment]
@carldlaird I agree that this might be useful to include a utility function for this.  My comment above concerns whether it's easy to already do this.  It is.

The question of whether/when to embed functionality like this in a utility function can be subtle, since it depends on whether the code will actually be reused.  I like your suggestion of putting utility functions someplace other than pyomo.core.  pyomo.contrib would be reasonable, and there was a suggestion for another 'util' subpackage in pyomo, right?

**Comment by qtothec** [comment]
@whart222 Yep, the 'util' discussion is in #211 and #217. I think that this is on the docket for the early January IDAES meeting at Sandia.

@jsiirola There is no specific breakout session in the draft schedule that David sent out where we can have a detailed code discussion, unless we count your 9:30 Pyomo update. Should we ask him for one?

**Comment by eslickj** [comment]
Yeah this is actually pretty trivial.  The way to do it sounds like what I'm doing.  Calculating the problems degrees of freedom, is fairly time consuming because it takes a while to iterate through large problems. So the utility function is good, but I was more wondering if there was a faster way that already exists.  I'll go ahead and close this issue.
