### ISSUE TITLE
Appsi build fails due to not having pybind11

### ISSUE THREAD

**Issue by codykarcher** [Pyomo/pyomo#2919]
## Summary

Building the extensions and `appsi` failed due to not having `pybind11`

The package `pybind11` is listed in  `setup.py`, line 229 as optional for running tests, but does not appear to be listed as required

### Steps to reproduce the issue

```console
$ pip install pyomo
$ pyomo download-extensions
$ pyomo build-extensions
```

### Error Message
Many things happened before this, but the relevant message is:
```console
**** Building APPSI ****
ERROR: ModuleNotFoundError: No module named 'pybind11'
```

### Information on your system

Pyomo version: 6.6.1
Python version: 3.9.12
Operating system: MacOS Ventura 13.3
How Pyomo was installed (PyPI, conda, source): pip
Solver (if applicable): N/A

### Additional information

Recommend either adding the `pybind11` package to the required dependencies in `setup.py` or closing this issue as out of scope.  Or making me do it myself.

**Comment by michaelbynum** [comment]
Unfortunately, this is not going to get fixed. We prefer to keep the number of Pyomo dependencies at a minimum. There are various modules throughout Pyomo that are not required for using the core parts of Pyomo but do have their own required dependencies. We list these dependencies as optional because they are only needed if you want to use those modules. For example, NumPy is required to use PyNumero, but it is an optional Pyomo dependency. Pybind11 is required to install the appsi extensions, but it is not needed for Pyomo in general (even parts of Appsi don’t need it). I, personally, am not aware of any good solutions for this kind of thing.

Anyway, if you want to compile the Appsi extensions, `pip install pybind11` should fix the problem. If you needed one of the other Pyomo extensions (e.g., PyNumero), then you can ignore the error.

**Comment by codykarcher** [comment]
Understood, makes sense.  Closing due to this being out of scope.

For future reference, the solution above of `pip install pybind11` worked for me.
