### ISSUE TITLE
Inconsistent Param mutability with units

### ISSUE THREAD

**Issue by bknueven** [Pyomo/pyomo#3002]
## Summary
Utilizing the `units` keyword argument in `Param` leads to some unexpected behavior:
1. The `Param` is `mutable` by default.
2. Manually specifying `mutable = False` still returns a `mutable` Param.

I am sure there's technical limitations around having non-mutable Params with units. That said, I would have expected (2) to raise an error.

### Steps to reproduce the issue

```python
>>> from pyomo.environ import *
>>> m = ConcreteModel()
>>> m.p_with_units = Param(initialize=42, units=units.m**2/units.s)
>>> m.p_with_units.mutable
True
>>> m.p_with_units_non_mutable = Param(initialize=42, units=units.m**2/units.s, mutable=False)
>>> m.p_with_units_non_mutable.mutable
True
```

### Information on your system

Pyomo version: 6.6.2
Python version: 3.10.9
Operating system: macOS
How Pyomo was installed (PyPI, conda, source): PyPI
Solver (if applicable): N/A

**Comment by jsiirola** [comment]
`Params` with units must be mutable: if `mutable==False`, then the expression system is allowed to simplify things as it generates expressions.  Because the units are stored on the Param, if we were to simplify the Param (and replace it with raw floats), then we would lose the units.

It is a good point that (explicitly) specifying `mutable=False` should at least issue a warning (I don't think an exception is necessary).  I'll get a PR up shortly.
