### ISSUE TITLE
Exiting of Pyomo

### ISSUE THREAD

**Issue by LoukasKyriakidis** [Pyomo/pyomo#3007]
## Summary

I am currently using Pyomo 6.4.2. with IPOPT as a solver for a nonlinear constrained optimization problem in Python 3.8.12. in Windows 10. The optimization problem has a dimension of 408. When I run the optimization, I sometimes get the following error:

**Restoration phase converged to a point with small primal infeasibility

EXIT: Restoration Failed!

ValueError: Cannot load a SolverResults object with bad status: error**

This error does not appear every time I optimize this particular problem. I sometimes get this error and sometimes it works without any problem.

I read on internet that this indicates that the restoration phase failed to find a feasible point that was acceptable to the filter line search for the original problem. This could happen if the problem is highly degenerate, does not satisfy the constraint qualification, or if the NLP code provides incorrect derivative information. Consequently, Pyomo stops the optimization and exits instead of continuing with a new starting point.

In addition, I realised that I don't get this error if I optimize problems of lower dimension.

### Error Message

Restoration phase converged to a point with small primal infeasibility

EXIT: Restoration Failed!

ValueError: Cannot load a SolverResults object with bad status: error

### Information on your system

Pyomo version: 6.4.2
Python version: 3.8.12
Operating system: Windows 10
How Pyomo was installed (PyPI, conda, source): conda
Solver (if applicable): ipopt

**Comment by jsiirola** [comment]
@LoukasKyriakidis, the "restoration failed" error is being emitted by ipopt and not by Pyomo (there is nothing that Pyomo can do about it).  As you found, Ipopt will issue this error when the feasibility restoration phase is unable to restore feasibility, and is generally due to a modeling (not software) issue (degeneracy, scaling, or violated LICQ).  If you believe that this is an error in Ipopt, you should report it to the Ipopt project.

You have also removed the "Steps to reproduce the issue" section of the issue template.  Without a minimal example that reproduces the issue, there is little we can do to help.
