### ISSUE TITLE
Bug using numpy float values in Pyomo expressions.

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#31]
Consider the following script:

```
# pyomo 4.4.1
# python 3.5
from pyomo.environ import *
import numpy

m = ConcreteModel()

m.T = RangeSet(10)
m.v = Var(initialize=1, bounds=(0,None))
m.c = Var(m.T, initialize=20)

def rule(m, t):
    h = numpy.float32(1.0)
    # This works
    return m.c[t]  == h * m.c[t]
m.X = Constraint(m.T, rule=rule)

def rule(m, t):
    h = numpy.float32(1.0)
    # This works
    return m.c[t]  == h * m.c[t] * m.v
m.X = Constraint(m.T, rule=rule)

def rule(m, t):
    h = numpy.float32(1.0)
    # This fails
    return m.c[t]  == h * m.v
m.x = Constraint(m.T, rule=rule)
```

The first two constraints are constructed fine, but the last one fails, generating the following error:

```
ERROR: Rule failed when generating expression for constraint x with index 1:
    KeyError: "Error accessing indexed component: Cannot treat the scalar component 'v' as an array"
ERROR: Constructing component 'x' from data=None failed:
    KeyError: "Error accessing indexed component: Cannot treat the scalar component 'v' as an array"
Traceback (most recent call last):
  File "tmp.py", line 26, in <module>
    m.x = Constraint(m.T, rule=rule)
  File "/Users/wehart/home/src/python35/src/pyomo/pyomo/core/base/block.py", line 483, in __setattr__
    self.add_component(name, val)
  File "/Users/wehart/home/src/python35/src/pyomo/pyomo/core/base/block.py", line 849, in add_component
    val.construct(data)
  File "/Users/wehart/home/src/python35/src/pyomo/pyomo/core/base/constraint.py", line 736, in construct
    ndx)
  File "/Users/wehart/home/src/python35/src/pyomo/pyomo/core/base/misc.py", line 59, in apply_indexed_rule
    return rule(model, index)
  File "tmp.py", line 25, in rule
    return m.c[t]  == h * m.v
  File "/Users/wehart/home/src/python35/src/pyomo/pyomo/core/base/indexed_component.py", line 499, in __getitem__
    raise KeyError(msg)
KeyError: "Error accessing indexed component: Cannot treat the scalar component 'v' as an array"
```

**Comment by jsiirola** [comment]
This is due to two things: one is our fault, and one is NumPy's.  Operator overloading in python works as follows:
 1. assume a binary operator `x * y` where `x` and `y` are instances of unrelated classes (i.e., `isinstance(x, type(y)) == isinstance(y,type(x)) == False`)
 2. If `x` implements `__mul__`, then Python calls `x.__mul__(y)`.
 3. If `x.__mul__(y)` returns NotImplemented (or `x` does not implement `__mul__`), then Python will call `y.__rmul__(x)`

So, since both Pyomo and NumPy work through operator overloading, all the classes in question implement both `__mul__` and `__rmul__`.  This means we first hit NumPy's `__mul__` method.  That method looks at `y`, sees that it implements `__getitem__` (or maybe `__len__`), and assumes that the class is a valid 0-indexed array.  It then tries to access `y[0]` to perform the operation.  We disallow this (the implicit index for Simple `IndexedComponents` is `None`) and raise an exception.

It is not a problem for your first two examples because the `c[t]` returns a `_VarData` (and not a `SimpleVar`).  `_VarData` does not present a "vector-like" interface, so NumPy treats it like a scalar and the normal operator overloading rules work out just fine.

So, how to fix this? I see several alternatives:
 1. Disallow treating Simple `IndexedComponents` as if they are implicitly indexed.  That is really not doable with the current object model, but might be implementable with the component_storage_interface branch.
 2. Get NumPy to catch exceptions encountered during operator overloading and then return `NotImplemented`.  Python would then call `y.__rmul__(x)`.  Our overloading is aware of NumPy-like things and would do the right thing.
 3. Allow implicitly indexing Simple `IndexedComponents` with `[0]`.  This will work around the immediate problem of the overload, but would cause other problems elsewhere: the return value from the NumPy overloaded operator is actually a `numpy.ndarray`.  We would need to augment our `generate_expression` code for both expression systems (and all components that accept expressions) to specifically check for `ndarray` objects with length 1 and extract the subexpression from them when generating expressions.
 4. [The quick-and-dirty workaround]  Write your expressions as `y * x`.  That is, make sure the Pyomo object is the first thing and not the last thing.  That way, Python hits our `__mul__` method first and The Right Thing(tm) happens

Overall, I think I like Option 3 the best.  I don't like putting special traps for NumPy in our core code, but at the same time this keeps coming up.  This also hints at a way to support vector/matrix constraints in Pyomo (it might be as simple as wrapping the pyomo components in NumPy `ndarray` objects and relying on NumPy!).

**Comment by ghackebeil** [comment]
Nice analysis, John.

I have come across cases where an indexed Pyomo variable with a list-like index ([0,n]) were able to successfully perform a vector multiplication with a numpy array. This always felt like a happy accident to me, but your explanation clears that up for me. We should definitely take a closer look at this in the future.

**Comment by whart222** [comment]
@jsiirola I don't think I understand your analysis.  Consider the following simple example, where class T defines __mul__ and __rmul__.  Why does this work but Pyomo fail?

```
class T(object):
  def __init__(self, val):
    self.val = val

  def __mul__(self, x):
    print("mul")
    return T(self.val*x)

  def __rmul__(self, x):
    print("rmul")
    return T(self.val*x)

  def __repr__(self):
    return str(self.val)

  def __getitem__(self, index):
    raise IOError


t = T(0.2)
import numpy as np
f = np.float64(0.9)

print(t*f, type(t*f))
print(f*t, type(f*t))
```

This prints the following values:

```
mul
mul
0.18 <class '__main__.T'>
rmul
rmul
0.18000000000000002 <class '__main__.T'>
```

My understanding of John's analysis is that this example should generate an error because __getitem__ raises an exception.  But it seems to work.

**Comment by ghackebeil** [comment]
@whart222 : As John mentioned, numpy might be checking for __len__ rather than __getitem__ (or both) on the object. If you add one (that returns 1), then you will see the IOError.

**Comment by jsiirola** [comment]
@whart222: I was speculating how NumPy determined that an argument was a scalar or list-like thing.  Looking at the NumPy code is really not an option (it is quite dense, and most of the magic happens in the compiled libraries).  However, with a little experimentation, it appears to be the existence of a `__len__(self)` method.  That is, if you add:

    def __len__(self):
        return 1

to your class `T`,then you will see the expected IOError:

    mul
    mul
    (0.18, <class '__main__.T'>)
    Traceback (most recent call last):
      File "test-numpy.py", line 28, in <module>
        print(f*t, type(f*t))
      File "test-numpy.py", line 20, in __getitem__
        raise IOError
    IOError

**Comment by whart222** [comment]
Ah.  I see that now.

**Comment by whart222** [comment]
Given that we're supporting len(), I think it's rational to allow Simple
components to be indexed by zero.

**Comment by ghackebeil** [comment]
It might also be worth running some experiments to see if the existence of a "shape" attribute affects how numpy interacts with objects. It might be that numpy detects scalars by check if ```x.shape == ()```.

**Comment by whart222** [comment]
No.  Adding the shape method doesn't help.

On Fri, Aug 26, 2016 at 1:21 PM, Gabriel Hackebeil <notifications@github.com

**Comment by whart222** [comment]
FYI, I just tried allowing simple components to be indexed by zero.  It didn't fix this example, since it generated another error.  If a simple variable is treated as a vector, then 
`h * m.v`
returns a list or length one.  And then our expression logic breaks.  :(

**Comment by sashwatroy11** [comment]
Any workaround for this?

**Comment by sashwatroy11** [comment]
Trying to add a constraint using a dataframe column.
Error Message:"Cannot treat the scalar component 'PVtoB'as an indexed component"

model.PVtoB = Param(initialize=df.PVGeneration.tolist(), doc='PV Generation')

def market_constraintx1(model, t):

        return (model.Charge[t]<= model.PVtoB[t])

    model.market_rulex1 = Constraint(model.T, rule=market_constraintx1)

**Comment by qtothec** [comment]
You need to specify an index on the Param: `model.PVtoB = Param(model.t, initialize=...)`

**Comment by sashwatroy11** [comment]
Thank you. When I do that I am getting an error: TypeError: can't multiply sequence by non-int of type 'float'.

**Comment by whart222** [comment]
I am closing PR #562, since this is stale.  I think that this PR does not completely resolve whether numpy data can be used with Pyomo models.  See my comment above from Oct 30, 2016.

I've moved the development branch here:  https://github.com/whart222/pyomo/tree/issue_31
