### ISSUE TITLE
NL writers linear presolver fails when one variable is left

### ISSUE THREAD

**Issue by bknueven** [Pyomo/pyomo#3192]
## Summary
The NL writer's linear presolver will fail if a single variable is left in the model.

### Steps to reproduce the issue

```python
from pyomo.environ import *                                                                                                                          

m = ConcreteModel()
m.x = Var(bounds=(0, None))
m.y = Var()
m.c = Constraint(expr = m.y == m.x)
m.o = Objective(expr=0)

s = SolverFactory("ipopt_v2")
# s.config.writer_config.linear_presolve = False
s.solve(m)
```

### Error Message

```console
Traceback (most recent call last):
  File "/Users/bknueven/Software/pyomo_test.py", line 11, in <module>
    s.solve(m)
  File "/Users/bknueven/Software/pyomo/pyomo/contrib/solver/base.py", line 522, in solve
    results: Results = super().solve(model)
  File "/Users/bknueven/Software/pyomo/pyomo/contrib/solver/ipopt.py", line 318, in solve
    nl_info = self._writer.write(
  File "/Users/bknueven/Software/pyomo/pyomo/repn/plugins/nl_writer.py", line 409, in write
    return impl.write(model)
  File "/Users/bknueven/Software/pyomo/pyomo/repn/plugins/nl_writer.py", line 1086, in write
    _vmap[_id] = nl.rstrip() % tuple(_vmap[_id] for _id in args)
  File "/Users/bknueven/Software/pyomo/pyomo/repn/plugins/nl_writer.py", line 1086, in <genexpr>
    _vmap[_id] = nl.rstrip() % tuple(_vmap[_id] for _id in args)
KeyError: 140241181484176
```

### Information on your system

Pyomo version: main (f8b02390e3a6e4c14c6486f2c969482f3420ccfb)
Python version: 3.10.9
Operating system: macOS
How Pyomo was installed (PyPI, conda, source): source
Solver (if applicable): N/A

### Additional information

Turning off the linear presolver gives the expected result.

**Comment by jsiirola** [comment]
OK - this is an interesting edge case: you have a model with a non-square subsystem that can be completely presolved out of the model. That is, there is a set of _n_ constraints that act on _m_ (with _m_>_n_) variables, and those variables do not appear in any other constraints / objectives.  In the original writer (or the new writer with presolve off), those variables and constraints are sent to the solver and the solver will pick (random) values for the _m-n_ degrees of freedom.  After presolve, the _n_ constraints are removed from the model - so when the writer collects / categorizes the model variables, none of the _m_ variables are found.  This is generally fine - but causes issues when we attempt to find values for the eliminated variables (as the _m-n_ degrees of freedom are not in the `var_map`).

What do you think the expected behavior should be?
1. leave the variables removed from the model alone (and they will be marked stale)
2. arbitrarily pick a value for the DOF and propagate the values through; but which value to pick?
  a. pick a value as close to 0 as allowed by the bounds
  b. pick the lower (or upper) bound
  c. pick the midpoint between the bounds

I think I would start with proposing 2.a.

**Comment by bknueven** [comment]
I tried out a few different LP solvers, and their own preprocessing techniques tend to pick a bound -- and this is what an active set method without presolve does too. But if you use an interior point method without presolve you get something closer to 2.c. If the free variable(s) don't have any bounds you seem to get 0.

So I agree that 2.a is the best of the options available. It conforms to existing practice while not being onerous to implement and maintain.

**Comment by blnicho** [comment]
2.a was the consensus when this was discussed at the Pyomo dev call
