### ISSUE TITLE
Reconsider performance of expressions with many constants

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#324]
Should we combine these into a single sum (which is expensive)?  Or store them in a list?

Right now, the Sum() function doesn't recognize that:

  1 + x + y

is a linear expression, because it starts with a constant and we're very conservative assuming that more than one constant term is a problem.

**Comment by carldlaird** [comment]
We probably need a longer discussion about this. I don’t really understand the performance issue. I will say the following:


1)       Recognizing certain specialized expression forms for efficient representation will obviously have tradeoffs (time required to recognize and rebuild is longer than the efficiency gain), and I am comfortable with wherever this happens to fall.

2)       There will be times when we want to ask the question “Is this expression linear?” or “Is this expression linear w.r.t. this variable?” or “Which variables appear linearly in this expression?”, and for more, sub “linear” with “quadratic”, etc. Of course, these will have to be *correct*, regardless of the cost, since they are likely to be used in a transformation or meta-solver, or something.

Carl.

**Comment by jsiirola** [comment]
Archived on the master Performance Proposals Issue (#1430).  Closing this performance proposal until active development has begun.
