### ISSUE TITLE
pyomo solve --log bug

### ISSUE THREAD

**Issue by jrlooker** [Pyomo/pyomo#35]
Hi,

When I run, for example, pyomo solve --log --solver=glpk diet1.py diet.dat the following error is produced:

ERROR: Unexpected exception while running model:
	'str' object has no attribute '_log_file'

Otherwise, the --log option appears to be working. This message is generated on two different machines with different OS, on different problems and solvers.

Is this a bug?

Thanks,
Jason

**Comment by ghackebeil** [comment]
I’m not familiar with the “--log” option, but it must be a bug. I am familiar with the “--stream-solver” option, which causes the solver log to be printed to the screen. Does anyone know what the difference between these two options is? Do we need both?

> Otherwise, the --log option appears to be working.
> 

Out of curiosity, what is the “otherwise” scenario where the “--log” option works? Is it when you use a different solver?

Gabe

**Comment by jrlooker** [comment]
Thanks for the quick response. FYI, I'm very new to pyomo. I can't even remember how I found the --log option. 

When --log is specified, a log file is created in a system tmp dir. This is what I meant by "Otherwise, the --log option appears to be working". 

This log file contains output that appears to be identical to the output created when the --stream-solver option and opt.solve(instance, **tee=True**) are specified. These approaches actually do what I was wanting, so I will no longer use the --log option.

Thanks again,
Jason

**Comment by jrlooker** [comment]
Thanks, William.
