### ISSUE TITLE
Parameter obfuscation with kwds.pop

### ISSUE THREAD

**Issue by tkorvola** [Pyomo/pyomo#360]
This pattern is very common in Pyomo:

    def foo(**kwds):
        bar=kwds.pop('bar', None)
        baz=kwds.pop('baz', None)
        # Pass the remaining kwds somewhere or throw if kwds.

Why so complicated? The obvious way to write this would be

    def foo(bar=None, baz=None, **kwds):

if you are going to pass on `kwds` and without `**kwds` if you want an exception for unknown keywords. This would allow `help(foo)` to display a more useful parameter list.

**Comment by jsiirola** [comment]
This idiom pops up for Pyomo component constructors.  The problem is that early on Pyomo made the decision to use one or more positional arguments to indicate indexing sets.  That is, the actual method prototype is:
```
def foo(*args, **kwds):
   # ...
```
When you place the optional arguments explicitly in the method declaration (like your `bar` and `baz`), they must be specified *before* `*args`.  As Python allows callers to provide them as positional arguments, this would confuse the indexing notation.  Recent versions of Python 3 support an extended syntax that allows you to declare explicit arguments and *force* the caller to specify them as keyword arguments; however, that syntax does not port back to Python 2, so we can't use it.

If you see that idiom outside of Component constructors, then developers may have just been lazy and your suggestion likely makes sense.  Please feel free to open issues against specific instances -- or better yet, submit Pull Requests!  :)
