### ISSUE TITLE
Test compatibility with old GLPK versions

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#404]
It looks like recent updates to Pyomo to work with GLPK 4.65 break compatibility with older versions of GLPK.  In particular, I've observed test failures with GLPK 4.40.

We should confirm Pyomo execution with a reasonable range of older GLPK versions.  Perhaps versions released in the last year?

**Comment by whart222** [comment]
@jsiirola Confirmed this behavior independently with 4.40, 4.52, and 4.57.

**Comment by blnicho** [comment]
@whart222 could you clarify if this is a compatibility issue (calls to the solver fail) or a solution returned by GLPK doesn't match the baseline test?

In #382 I point to a forum post that claims there are inconsistencies in GLPK itself where certain versions of the solver return the wrong answer for some problems. So in order to get solver-based Pyomo tests to work for a range of GLPK versions we have to be careful to formulate models where this bug in GLPK does not arise. We should also verify the solutions in our baselines using a solver other than GLPK to make sure they are correct.

**Comment by jsiirola** [comment]
The `TerminationCondition` returned by GLPK for a set of test problems in `pyomo.solvers.tests.checks.test_writers` changes (I believe that they return 'optimal' when we expect either unbounded' or 'infeasibleOrUnbounded').  It is likely an issue with our parsers... we have three different interfaces for GLPK (<4.42, 4.42-4.57, >= 4.58) - and this looks like an issue with the first two (oldest) interfaces.

As both Jenkins and Travis test with current versions, these errors have likely been in the codebase for a long time (@whart222 stumbled across it because he was inadvertently using the system default glpk on an old machine).
