### ISSUE TITLE
Define a location for logical functions

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#414]
We've started using Expr_if() to define a logical IF clause.  But there are other logical functions that we should consider supporting:  ThereExists(), ForAll(), etc.

I think we should put these in a well-named package that provides scoping for these functions.  For example, the following might make sense:
```
from pyomo.environ import *

expr = logical.IF( ... )
```

**Comment by DLWoodruff** [comment]
I know we have this sort of argument all the time, which is why I know that there are good reasons why someone might want to use a beautiful, elegant, and therefore overloaded word like "logical" for this package, but these sorts of names cause a lot of trouble for new users.  That being said, "logical" is way better than "logic" for the name of this package, IMO.  New users could live with "Logical" but for them, something like "Logic_expr" would avoid overload.

**Comment by whart222** [comment]
I think this should be in pyomo.core.  This is also needed for constraint programming as well.

**Comment by carldlaird** [comment]
The Expr_If is fundamentally different from the logical expressions involved in GDP, no? This is really a direct mapping of the AMPL equivalent which is primarily used to piece together continuous (and hopefully smooth) piecewise functions. Whereas logical expressions presumably work on logic variables and would require some transformation or decomposition for solution?

**Comment by whart222** [comment]
@carldlaird In its current usage, you are correct.  But if a user declared Expr_If with a logical variable as its first argument, then that usage would be similar to these other methods.

**Comment by carldlaird** [comment]
OK, I would just want to make sure we don't complicate it's current usage/purpose if we expand it to other purposes.

**Comment by whart222** [comment]
Creating separate logical expression trees will help with that, but I suspect we'll have some complications along these lines.

**Comment by blnicho** [comment]
This was completed in #1507.
