### ISSUE TITLE
Unable to pass solver options to neos

### ISSUE THREAD

**Issue by jrlooker** [Pyomo/pyomo#47]
Hi,

I'm using the neos solver manager with the cplex solver, but I appear to be unable to pass solver options.

Note that I can pass options to solvers on my local machine.

Is this a bug? Do you have any suggestions?

Thanks,
Jason

**Comment by ghackebeil** [comment]
I can confirm this is an issue on trunk.

@whart222: Can you take a look it this? You are setting a lot of local environment variables in the NEOS plugin related to solver options, and I'm not sure I understand how you meant for that to work. Here is an example you can start from:

```python
from pyomo.environ import *

model = ConcreteModel()
model.x = Var()
model.c = Constraint(expr=model.x >= 1)
model.o = Objective(expr=model.x)

opt = SolverFactory("cplex")
opt.options["outlev"] = 10
solver_manager = SolverManagerFactory('neos')
results = solver_manager.solve(model,
                               opt=opt,
                               tee=True)
```
It's easy to verify that no solver options are being sent because they do not appear in the xml data being uploaded to NEOS. It would also be great if we could somehow download the solver log from NEOS (rather than just the solution file). This would help verify that options are being received.

**Comment by whart222** [comment]
You can use the 'logfile' option in the solve() method to specify a local logfile.  But this doesn't currently show the solver output.  I suspect that that is a NEOS-specific issue that we'll have to follow-up on.

**Comment by jrlooker** [comment]
Thanks, William.
