### ISSUE TITLE
Recursion error when constructing Var indexed on [None]

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#6]
I suspect that something to do with process_setargs is causing a recursion error in the following example:

```
m = ConcreteModel()
m.x = Var([None])
```

In case this seems like a silly thing to do, I encounter it when I am trying the following:

```
m = ConcreteModel()
m.x = Var()

m2 = ConcreteModel()
m2.x = Var(m.x._index)
```

In this case, I could just use clone instead, but if I am just trying to clone certain variables, that would be overkill.

**Comment by ghackebeil** [comment]
Although it seems like a logical thing to do, the appearance of args in the Var constructor will create a different type of variable (IndexedVar). This is due to our use of __new__ when creating components. Cloning is probably the best way to go for now.

Gabe

**Comment by ghackebeil** [comment]
Another thing to do would be to modify your example to check for the singleton case:
```#!python
m = ConcreteModel()
m.x = Var()

m2 = ConcreteModel()
if m.x.is_indexed():
   m2.x = Var(m.x._index)
else:
   m2.x = Var()
```

Or you could place the code that adds "x" inside of a common function that you call to modify a model object. You could also place the group of variables that you want "cloned" on a sub-block of the model and clone that. E.g.,

```#!python
m = ConcreteModel()
m.b = Block()
m.b.x = Var()

m2 = ConcreteModel()
m2.b = m.b.clone()
```

**Comment by qtothec** [comment]
Thanks Gabe. I eventually did go with checking for the singleton case. It may be quibbling at this point, but it seems like the check for is_indexed occurs a lot. What got me into this mess was something to the effect of:

```
m = ConcreteModel()
m.b = Block()
m.b.x = Var(...)
m.b.y = Var(a_set, ...)
m.b.other_vars = Var(...)
...

nvar = # of vars in m.b
var_set = RangeSet(nvar)

m2 = ConcreteModel()
m2.b = Block()
for var in m.b.component_map(ctype=Var, active=True):
    m2.b.add_component(var.cname(), Var(var._index * var_set, ...))
```
which feels like it should work, but actually requires a bit of Var is_indexed checking.

**Comment by jsiirola** [comment]
I just committed a fix to core that corrects the infinite recursion and allows the use case that Qi reported:

```python
>>> from pyomo.environ import *
>>> m = ConcreteModel()
>>> m.x = Var()
>>> m.I = RangeSet(3)
>>> m.y = Var(m.x._index, m.I)
>>> m.pprint()
2 Set Declarations
    y_index : Dim=0, Dimen=2, Size=3, Domain=None, Ordered=False, Bounds=None
        Virtual
    y_index_0 : Dim=0, Dimen=1, Size=1, Domain=None, Ordered=False, Bounds=None
        [None]

1 RangeSet Declarations
    I : Dim=0, Dimen=1, Size=3, Domain=Integers, Ordered=True, Bounds=(1, 3)
        Virtual

2 Var Declarations
    x : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :  None :  None :  None : False :  True :  Reals
    y : Size=3, Index=y_index
        Key       : Lower : Value : Upper : Fixed : Stale : Domain
        (None, 1) :  None :  None :  None : False :  True :  Reals
        (None, 2) :  None :  None :  None : False :  True :  Reals
        (None, 3) :  None :  None :  None : False :  True :  Reals
```

Note that you cannot do the truly obvious thing that Qi wants:
```
>>> m.y = Var(m.x._index*m.I)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for *: 'set' and 'RangeSet'
```
because the operator overloading doesn't allow multiplication between a Python `set` and a Pyomo `Set`.  I am reopening this, because there are still some gotchas.  In particular, if you initialize a component with:
```python
m.x = Var(set([None]))
```
thinking that you will get an IndexedVar, you will actually get a SimpleVar.  I think the final resolution is to create a proper component in lieu of the UndexedComponent_set global.  This will prevent model.clone() from duplicating it and allow us to use "is" instead of "==" to test for "is_indexed".  With that, we can deterministically distinguish between these two uses.  The only thing that will make closing out this ticket a bit tricky is a circular reference between sets.py and indexed_component.py.

**Comment by qtothec** [comment]
Since you're looking at this, if I really had my way, `y` in your example would be indexed over `[1, 2, 3]` rather than `[(None, 1), (None, 2), (None, 3)]`

**Comment by jsiirola** [comment]
Alas, it is not likely that we will ever support that simplification: taking the cross product of two "Sets" and getting a 1-dimentional set just seems a bit nonintuitive.

**Comment by qtothec** [comment]
I can see that perspective. I was thinking about it a slightly different way: since `x` is not actually indexed and the `set([None])` is implicit, there is only one set involved: `z = set([1, 2, 3]); set(itertools.product(z))`, yielding `set((1,), (2,), (3,))`.

**Comment by jsiirola** [comment]
I see.  Now, to turn your argument on it's head:  If you assume that your first set is empty, then (per itertools), you wouldn't get what you want:
```python
>>> list(  itertools.product(set([]), set([1,2,3])) )
[]
```
The trick here is that since there *is* a value (`_VarData`) for the first `Var`, there logically must be a non-empty index.  (In contrast, it is perfectly legitimate to have a `Var([])`, which has no entries).  When scripting in Pyomo, it's best to think of all components as if they are indexed -- if you find yourself doing something strange requiring `is_indexed` tests (apart from pretty output formatting), you have probably found a bug in Pyomo.

**Comment by qtothec** [comment]
That's fair. I think I may just have a perfectionist's aversion to having a bunch of `None`s running around. When I lift a variable, say `x` to a higher dimension, I like the look of `x_1, x_2, x_3` more than `x_None,1; x_None,2; x_None,3`. The only way I know of to accomplish this is using `is_indexed` tests. This detail isn't high-priority for me, though.
