### ISSUE TITLE
GDP internal variable names raise problems when translating to GAMS

### ISSUE THREAD

**Issue by bernalde** [Pyomo/pyomo#683]
When using the GAMS solver to solve a model that has been transformed using the `TranformationFactory` bigM or chull specifying the option `symbolic_solver_labels=True`, Pyomo generates a GAMS file which constains equations and variables with names starting with a _ (e.g. `_gdp_bigm_relaxation_disjunction_xor`) or with double underscore __ (e.g. `d_0__indicator_var`). This raises issues when solving it with GAMS, specifically errors 409, 109 (and sometimes 119 because the variables names become too large).
Although the easy way to deal with this would be just to use the default option  `symbolic_solver_labels=False`, this issue appeared when working with @MAZamarripa in an Ideas-Related project, where the user is still interested on looking at the generated GAMS file.
I'm attaching a MWE, with its generated outputs in GAMS. Maybe just removing this 'underscored' names or hashing names of equations/variables with more than X characters can be a way of solving this.

[issue_gdp_gams.zip](https://github.com/Pyomo/pyomo/files/2362026/issue_gdp_gams.zip)

**Comment by qtothec** [comment]
This is a duplicate. I'm almost positive that I discussed this with Grant at some point. There might also already be a solution.

**Comment by gseastream** [comment]
I just tried this on the master branch and with GAMS 24.8.5, and one of these issues still exists: the writer still generates gms files with names starting with underscores. However, #512 fixed the issue about symbol names being too long. Additionally, GAMS does not seem to have any issue with symbols containing double underscores.

Should we change the labeler that the GAMS writer uses to make sure exported symbols do not start with underscores? Otherwise we should change the GDP transformations.

**Comment by qtothec** [comment]
Wow, I can't believe I've been out of action for so long that I missed this. Yeah, changing the labeler would be a good idea.

**Comment by gseastream** [comment]
@qtothec which labeler do you think should be changed? Make GAMS modify symbols starting with underscores, or make GDP not generate symbols starting with underscores?

**Comment by qtothec** [comment]
@gseastream I would say change the GAMS writer. Use of underscore fairly common in Python.

**Comment by gseastream** [comment]
I suppose both could be done in an effort to future-proof both of them.

**Comment by qtothec** [comment]
@gseastream Did you actually ever get to this one? :upside_down_face:

**Comment by gseastream** [comment]
No, since it still felt like an open question on what to do

**Comment by qtothec** [comment]
I'm inclined to say that we modify the GAMS writer to modify symbols starting with underscores.

**Comment by gseastream** [comment]
Sounds fine to me. The labeler will need to be changed (or a new layer added) and we'll have to deal with name conflicts.

**Comment by gseastream** [comment]
So if the goal is to add a new layer to the labeler that checks if symbols start with underscores (or a number because that is also not allowed), and replace it with a safe character like 'x', is the only way to deal with name conflicts going to be a dictionary of existing names and making sure the new symbol doesn't already exist (and then perhaps incrementing a counter until the symbol is unique)? I don't know if this is undesired for any reason.... Feels like it might be slow or inefficient or something.
