### ISSUE TITLE
Design discussion for api modifications to "Reference"

### ISSUE THREAD

**Issue by carldlaird** [Pyomo/pyomo#690]
We should have a design discussion about the aliasing feature "Reference". Some issues raised include:
- By default the created reference has the same ctype as the source - this means that the reference acts like the component (including, for example, that the data objects show up twice when we call component_data_objects)
- If the ctype is set to None, the issue above does not happen, however, the reference does not print when we print the model (so we don't know it exists)

Need to ensure we have correct behavior in use cases, and also clear output to the user that it exists and where it points.

One idea was to change the default `ctype` to "`ComponentReference`", but we need to think through the ramifications of adding a new `ctype` has on the transformations/writers. 

Please add other thoughts to the discussion.

**Comment by gseastream** [comment]
Just quick thoughts, but when discussing this feature I never imagined it would be an actual component. It made more sense to me that it's just its own object that has just enough methods and attributes to act like a real indexed component (so that ports can handle them correctly, for example). When it's its own component then you have the issue mentioned above where data objects show up twice. It's related to the issue we've always avoided of not letting components appear more than once on a block or on more than one block.

**Comment by blnicho** [comment]
There was some relevant discussions on this in #909

**Comment by blnicho** [comment]
This issue has been duplicated in #1640 so I'm closing this.
