### ISSUE TITLE
Simple slices

### ISSUE THREAD

**Issue by cathywu** [Pyomo/pyomo#703]
I am trying to slice into a model variable, and I'm wondering: what constitutes a "simple slice"? I could not find an example in the code or documentation.

When trying to slice into a model variable `model.A2` using standard numpy slicing syntax, I get the following error:
```
~/solver.py in rule(model)
    449             map = np.ones(X,Y)
    450             total = summation(map, model.A)
--> 451             total += summation(map[:-1, :], model.A2[:-1, :])

~/anaconda/envs/project/lib/python3.6/site-packages/pyomo/core/base/indexed_component.py in __getitem__(self, index)
    529         except TypeError:
    530             obj = _NotFound
--> 531             index = self._processUnhashableIndex(index)
    532             if index.__class__ is _IndexedComponent_slicer:
    533                 return index

~/anaconda/envs/project/lib/python3.6/site-packages/pyomo/core/base/indexed_component.py in _processUnhashableIndex(self, idx, _exception)
    730                 if val.start is not None or val.stop is not None:
    731                     raise IndexError(
--> 732                         "Indexed components can only be indexed with simple "
    733                         "slices: start and stop values are not allowed.")
    734                 if val.step is not None:

IndexError: Indexed components can only be indexed with simple slices: start and stop values are not allowed.
```

**Comment by blnicho** [comment]
The slice notation in Pyomo does not have as many features as the slice notation in numpy. A slice using a colon can only be used to iterate over every valid index in that position. Slicing in Pyomo is relatively new so there isn't any documentation for it yet but take a look at [these unit tests](https://github.com/Pyomo/pyomo/blob/8cbe45bf0143f4d4793a55a8de8c901cb4528e3b/pyomo/core/tests/unit/test_indexed_slice.py) to get an idea of how it works.

**Comment by jsiirola** [comment]
Adding on to what @blnicho said, a "simple slice" is a combination of concrete values, bare colons (e.g., `model.x[:,3]`) and an optional ellipsis (`model.x[...]`).  A colon matches any value for a single "index" and an ellipsis matches 0 or more indices.  

We do not support bounds on slices for several reasons.  The main one is that Pyomo Sets are, by default, unordered, thus providing bounds on the slice is undefined (how do you know what is "between" the bounds if there is no defined order?).  Even for ordered sets, there is ambiguity: would the bounds on the slice be members of the set, or would they be ordinal values (your example above implies the latter, but I can think of many cases where the expected behavior would be the former).
