### ISSUE TITLE
Warn when Pyutilib out of sync with Pyomo

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#734]
We should emit some warning when importing PyUtilib of a version below what the Pyomo installation expects. I have had collaborators run into this problem, and #731 shows that other users encounter this as well.

**Comment by mfripp** [comment]
The reverse can also be a problem—running pyomo with a too-new version of Pyutilib. Today, I had to help a colleague trying to run our software which depends on Pyomo. It turned out we have an incompatibility with Pyomo 5.7. So I had her install Pyomo 5.6.6 to match my setup. But then she ended up with an incompatibility between Pyomo 5.6.6 and Pyutilib 6.0.0, which conda installed automatically with Pyomo 5.6.6.

I came here to request that the metadata for Pyomo 5.6.6 (and similar versions) on pypi and conda-forge be updated to require Pyutilib < 6.0.0. I think @qtothec's problem above may already have been solved by setting minimum versions of Pyutilib in the Pyomo metadata. 

However, I think this retroactive fix may not be possible—the repositories may freeze code for a particular version number as of the original release. So maybe future releases of Pyomo can be released with an upper limit on the version number of Pyutilib, corresponding to the point when they will go out of compatibility. (I know, that's unknowable, which makes this a fun problem.)

As another note: this was hard to debug, because Pyutilib reported that "Python 3 now has an enum implementation in the standard library (also available for older Python versions as the third-party enum34 PyPI package) that supersedes this library." So I thought this was an incompatibility between Pyomo 5.6.6 and Python 3.7.7 (used on the new machine), but then was surprised when I couldn't run `pyomo --version` even with Python 3.7.3. Even on my machine, if I created a new environment with exactly the same versions of Python (3.7.3) and Pyomo (5.6.6) as my base environment, I couldn't get Pyomo to run. But it still ran in my base environment with those versions. It turned out the problem was that Pyutilib 5.7.1 got installed when I created my base environment, but Pyutilib 6.0 was being installed along with Pyomo 5.6.6 into any new environments.

So maybe a partial solution would at least be to change the error in `pyutilib/enum/__init__.py` to say something like "enum has been removed from this version of pyutilib. Please update your code to use the native version in Python >= 3.X or install pyutilib 5.8 if you need backward compatibility."

**Comment by mfripp** [comment]
For what it's worth, it looks like you'd have to upload post-release versions like `5.6.6.post1` to pypi (and maybe similar for conda-forge) to update the metadata. That is discussed some here: https://stackoverflow.com/a/13919964/3830997

**Comment by milindsmart** [comment]
Related : https://github.com/Pyomo/pyomo/issues/1525

**Comment by jsiirola** [comment]
We are currently in the process of breaking the dependence on PyUtilib (and expect it to be completely removed for the Pyomo 6.0 release).  Much of the functionality in PyUtilib is either not used by Pyomo or no longer needed on recent Python versions.
