### ISSUE TITLE
Is pyomo equality expression commutative?

### ISSUE THREAD

**Issue by lafrech** [Pyomo/pyomo#794]
While working on a model defined with pyomo, I'm observing results I don't understand.

Here's a constraint defined by a function:

```py
    def my_constraint(model, j):
        a = sum(model.variable_1[i, j] for i in model.i) + sum(model.variable_2[o, j] for o in model.o if o != j)
        b = model.variable_3[j]
        # Apparently, the order matters !?
        return a == b
        # return b == a

    model.my_constraint = pe.Constraint(model.j, rule=my_constraint)
```

I assumed the order of the terms of the equality wouldn't matter but if I switch them, I get different results.

The generated .nl files differ slightly. Two thee-line sets have a sign difference.

File 1:

    [...]
    24 1
    32 -1
    35 1
    [...]
    25 1
    33 -1
    34 1
    [...]

File 2:

    [...]
    24 -1
    32 1
    35 -1
    [...]
    25 -1
    33 1
    34 -1
    [...]

When feeding both files to ipopt, I get "infeasible" with file 1 and a solution with file 2. If I edit file 1 to change the signs in either the first or the second three-line set, I get convergence with the same results as file 2.

So AFAIU the order in the equality of the expression should not matter, but when changing it, I get, in the .nl file, a sign difference that does matter.

I'm struggling to find an explanation to this and any hint would be greatly appreciated. I'm new to pyomo and model solving in general, so please excuse me if this is obvious.

Also posted on SO: https://stackoverflow.com/questions/53872031/is-pyomo-equality-expression-commutative.

**Comment by michaelbynum** [comment]
It is true that the optimal solution to an optimization problem does not change if you write a - b = 0 instead of b - a = 0. However, the path a solver takes may depend on how you write your problem, especially if the solver is having numerical difficulties. My guess is that even when you are getting a solution, Ipopt is having numerical difficulties. Take a look at the Ipopt output to verify.

Michael

On Jan 2, 2019, at 3:33 AM, Jérôme Lafréchoux <notifications@github.com<mailto:notifications@github.com>> wrote:


While working on a model defined with pyomo, I'm observing results I don't understand.

Here's a constraint defined by a function:

    def my_constraint(model, j):
        a = sum(model.variable_1[i, j] for i in model.i) + sum(model.variable_2[o, j] for o in model.o if o != j)
        b = model.variable_3[j]
        # Apparently, the order matters !?
        return a == b
        # return b == a

    model.my_constraint = pe.Constraint(model.j, rule=my_constraint)

I assumed the order of the terms of the equality wouldn't matter but if I switch them, I get different results.

The generated .nl files differ slightly. Two thee-line sets have a sign difference.

File 1:

[...]
24 1
32 -1
35 1
[...]
25 1
33 -1
34 1
[...]


File 2:

[...]
24 -1
32 1
35 -1
[...]
25 -1
33 1
34 -1
[...]


When feeding both files to ipopt, I get "infeasible" with file 1 and a solution with file 2. If I edit file 1 to change the signs in either the first or the second three-line set, I get convergence with the same results as file 2.

So AFAIU the order in the equality of the expression should not matter, but when changing it, I get, in the .nl file, a sign difference that does matter.

I'm struggling to find an explanation to this and any hint would be greatly appreciated. I'm new to pyomo and model solving in general, so please excuse me if this is obvious.

Also posted on SO: https://stackoverflow.com/questions/53872031/is-pyomo-equality-expression-commutative.

**Comment by qtothec** [comment]
@michaelbynum's answer is the most likely explanation for this effect, so closing as solved.

If your optimization problem is nonlinear and non-convex, then this not surprising behavior for a local NLP solver like IPOPT. You should get a consistent answer for both formulations from a global solver like BARON (if it is able to converge bounds).
If your model is linear, then there is likely a Pyomo issue.
