### ISSUE TITLE
Derived component IndexConstraint failed to define _default()

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#9]
Got the following error trying to refer to a Constraint that I skipped definition for.

```
File "/home/qtothec/pyomo/src/pyomo/pyomo/core/base/indexed_component.py", line 516, in _default
  % (self.__class__.__name__,))
NotImplementedError: Derived component IndexedConstraint failed to define _default().
    Please report this to the Pyomo developers
```

It's quite easy to produce this error:

```
from pyomo.environ import *
m = ConcreteModel()
m.x = Var()
def _c(b, i):
    if i == 1:
        return m.x == 1
    else:
        return Constraint.NoConstraint
m.c = Constraint([1, 2, 3], rule=_c)
print(m.c[2])
# or really anything else trying to refer to that _ConstraintData
# is going to give the above error
```

I'm not opposed to getting an error message in this case, since it was an error on my part, but the message should probably say something different.

Related to this, if I'm iterating over m.c._index, would be best way to check for existence be to use `indx in m.c`?

**Comment by ghackebeil** [comment]
You are highlighting an issue that I have with the current design, which is that there is really no enforced connection between an indexed component and the index set of that component after it is created. It would be clear why you can't expect to find an entry in m.c[2] if it was built in a for-loop:
```#!python
for i in range(3):
   if i == 1:
      m.c[i] = ...
```
but there are other ways that the index can diverge from the components "keys" list as well.

So yes, you are correct that it is not always safe to assume that everything in m.c._index can be used to access m.c. This is not only true for Constraint, but other components as well. The index may have had entries added to it (or deleted from it) since the time the constraint was constructed, or the constraint maybe have discarded "skipped" entries to save memory. The _index object is referring to a separate Set object (that may have been implicitly created), but the individual constraint objects are stored in a separate dictionary with its own set of keys.

I agree that the error message is not very helpful.

**Comment by jsiirola** [comment]
This specific error is indeed a "bug" that should be reported. In this specific case, it is not clear what should be returned as the default value for a constraint. Maybe Constraint.Skip? I'd like to keep this ticket open, but it may be a while before it is resolved (fixing it correctly may require an overhaul of _ConstraintData that is long overdue, but not a quick activity).

To follow on Gabe' comments: Because of things like `Param(default=x)` and `Constraint.Skip`, the `_index` will always be a superset of the defined values in the component. Put a different way, all indexed components are technically sparse (indeed, the class used to be `SparseIndexedComponent`). That is a design feature that is not likely to change any time soon.

On Jun 23, 2016, at 11:46 PM, Gabriel Hackebeil <notifications@github.com<mailto:notifications@github.com>> wrote:


You are highlighting an issue that I have with the current design, which is that there is really no enforced connection between an indexed component and the index set of that component after it is created. It would be clear why you can't expect to find an entry in m.c[2] if it was built in a for-loop:

for i in range(3):
   if i == 1:
      m.c[i] = ...


but there are other ways that the index can diverge from the components "keys" list as well.

So yes, you are correct that it is not always safe to assume that everything in m.c._index can be used to access m.c. This is not only true for Constraint, but other components as well. The index may have had entries added to it (or deleted from it) since the time the constraint was constructed, or the constraint maybe have discarded "skipped" entries to save memory. The _index object is referring to a separate Set object (that may have been implicitly created), but the individual constraint objects are stored in a separate dictionary with its own set of keys.

I agree that the error message is not very helpful.

**Comment by ikonikon** [comment]
Note that the same error message is shown when declaring a Constraint that has the same name as an already-defined pyomo model variable or parameter. Consider providing a message highlighting the name conflict instead of the more cryptic 'Derived component IndexConstraint failed to define _default()'.

**Comment by qtothec** [comment]
@ikonikon I'm surprised that you didn't first get a warning message about implicitly replacing existing component [blah] when doing so. Do you have a small example that reproduces this behavior?

**Comment by qtothec** [comment]
I think closing a single-digit issue is worth at least a mini-celebration. :cake: :balloon: :balloon: :tada:
