### ISSUE TITLE
Distinguishing References from other components

### ISSUE THREAD

**Issue by andrewlee94** [Pyomo/pyomo#909]
I am trying to write methods to enumerate and quantify the variables and constraints in my model in order to report model statistics (without needing to call a solver). However, my models include Pyomo `References` and I am looking for a way to distinguish these from actual components.

Consider the following example:

```
from pyomo.environ import *

m = ConcreteModel()
m.s = Set(initialize=[1,2,3,4])

m.v = Var(m.s, initialize=10)
m.r = Reference(m.v)

list_of_vars = []

for o in m.component_data_objects(ctype=Var, descend_into=True):
    list_of_vars.append(o.name)

print(list_of_vars)
```

What I would expect to see is a list containing the names of all the `Vars` in my model, i.e. `['v[1]', 'v[2]', 'v[3]', 'v[4]']`.

However, the result I get is: `['v[1]', 'v[2]', 'v[3]', 'v[4]', 'v[1]', 'v[2]', 'v[3]', 'v[4]']` - the `References` are being counted as `Vars`, as they have the same ctype as the component they reference.

This makes it difficult to correctly quantify the number of `Vars` (and any other component) in my model, as any component that is referenced is counted multiple times.

Is there an existing way to distinguish `References` from actual components, or is this something that should be addressed in Pyomo? I tried using `isinstance` in the hopes that it would work, but quickly realised that `Reference` is in fact a method rather than a class.

**Comment by qtothec** [comment]
References take the type of their referee so that `pprint()` works with them. If you want to have that list of vars, do `list(ComponentSet(m.component_data_objects(ctype=Var, descend_into=True)))`.

**Comment by jsiirola** [comment]
For good or ill, there is no such thing as a "Reference" object.  `Reference()` turns out to be a *function* that nominally returns a derivative of `IndexedComponent`.  If all the `_*Data`s referenced by the slice have the same ctype, then `Reference()` will return an instance of that ctype.  At that point, the only difference between the object returned from `Reference()` and a "normal" instance of that ctype is the type of the internal `_data` data structure: normal ctypes use `type(obj._data) is dict`, whereas the `Reference()` returns an object with `type(obj._data) is _ReferenceDict`.

If you don't want your references to be "indistinguishable" from normal components, you can pass your desired ctype to the call to `Reference()`.  The simplest thing is to use `Reference(..., ctype=None)`, which will return an instance of `IndexedComponent`.  You will lose some Component-level operators (like `pprint()`), but then the References will not be picked up by things like the `component_objects()` iterators.

**Comment by blnicho** [comment]
@andrewlee94 are the solutions proposed by @qtothec and @jsiirola sufficient to close this issue?

**Comment by andrewlee94** [comment]
@blnicho I was just about to say that I think this has been resolved (for me at least).
