### ISSUE TITLE
[PEP] Rename "Simple" components to "Scalar"

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#942]
## Proposal
Rename all "`Simple*`" components (`SimpleVar`, `SimpleBlock`, etc.) to "`Scalar*`" (`ScalarVar`, `ScalarBlock`, etc.).

## Motivation
There is nothing "simple" about the Pyomo Component API.  "Scalar" better represents what the "Simple" components are (it is a single thing), and more closely parallels the use of "Indexed" in the component hierarchy.

**Comment by DLWoodruff** [comment]
I like this idea. However, we should consider "Singleton" instead of "Scalar" since "Singleton" is more orthogonal to "Indexed" (under the appropriate definition of an inner product in the space of component names, of course).  Also, the concept of a scalar block seems strange to me but a singleton block seems quite natural.

**Comment by michaelbynum** [comment]
I am in favor of this change. However, I prefer "Scalar" to "Singleton" because "Singleton" is a software design pattern and means something very specific.

**Comment by whart222** [comment]
The use of 'Scalar' is consistent with the conclusion of our 2013 discussion on googlegroups.

**Comment by whart222** [comment]
Hence, my moment of deja vu when I saw this PEP.

**Comment by carldlaird** [comment]
I am in favor of this change. Although, I don't think this is hurting anyone right now, so I suspect it is lower priority.
